// Code generated by ent, DO NOT EDIT.

package actionresult

import (
	"fmt"
	"io"
	"strconv"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the actionresult type in the database.
	Label = "action_result"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldActionID holds the string denoting the action_id field in the database.
	FieldActionID = "action_id"
	// FieldChannelMessageID holds the string denoting the channel_message_id field in the database.
	FieldChannelMessageID = "channel_message_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldResultMessage holds the string denoting the result_message field in the database.
	FieldResultMessage = "result_message"
	// EdgeAction holds the string denoting the action edge name in mutations.
	EdgeAction = "action"
	// EdgeChannelMessage holds the string denoting the channel_message edge name in mutations.
	EdgeChannelMessage = "channel_message"
	// Table holds the table name of the actionresult in the database.
	Table = "action_results"
	// ActionTable is the table that holds the action relation/edge.
	ActionTable = "action_results"
	// ActionInverseTable is the table name for the Action entity.
	// It exists in this package in order to avoid circular dependency with the "action" package.
	ActionInverseTable = "actions"
	// ActionColumn is the table column denoting the action relation/edge.
	ActionColumn = "action_id"
	// ChannelMessageTable is the table that holds the channel_message relation/edge.
	ChannelMessageTable = "action_results"
	// ChannelMessageInverseTable is the table name for the ChannelMessage entity.
	// It exists in this package in order to avoid circular dependency with the "channelmessage" package.
	ChannelMessageInverseTable = "channel_messages"
	// ChannelMessageColumn is the table column denoting the channel_message relation/edge.
	ChannelMessageColumn = "channel_message_id"
)

// Columns holds all SQL columns for actionresult fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldActionID,
	FieldChannelMessageID,
	FieldStatus,
	FieldResultMessage,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Status defines the type for the "status" enum field.
type Status string

// Status values.
const (
	StatusSuccess          Status = "success"
	StatusMissingParameter Status = "missing_parameter"
	StatusFailed           Status = "failed"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusSuccess, StatusMissingParameter, StatusFailed:
		return nil
	default:
		return fmt.Errorf("actionresult: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the ActionResult queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByActionID orders the results by the action_id field.
func ByActionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActionID, opts...).ToFunc()
}

// ByChannelMessageID orders the results by the channel_message_id field.
func ByChannelMessageID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannelMessageID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByResultMessage orders the results by the result_message field.
func ByResultMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResultMessage, opts...).ToFunc()
}

// ByActionField orders the results by action field.
func ByActionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newActionStep(), sql.OrderByField(field, opts...))
	}
}

// ByChannelMessageField orders the results by channel_message field.
func ByChannelMessageField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChannelMessageStep(), sql.OrderByField(field, opts...))
	}
}
func newActionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ActionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ActionTable, ActionColumn),
	)
}
func newChannelMessageStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChannelMessageInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ChannelMessageTable, ChannelMessageColumn),
	)
}

// MarshalGQL implements graphql.Marshaler interface.
func (e Status) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *Status) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = Status(str)
	if err := StatusValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid Status", str)
	}
	return nil
}
