// Code generated by ent, DO NOT EDIT.

package todoevent

import (
	"fmt"
	"io"
	"strconv"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the todoevent type in the database.
	Label = "todo_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldTodoID holds the string denoting the todo_id field in the database.
	FieldTodoID = "todo_id"
	// FieldSourceCandidateID holds the string denoting the source_candidate_id field in the database.
	FieldSourceCandidateID = "source_candidate_id"
	// FieldSourceMessageID holds the string denoting the source_message_id field in the database.
	FieldSourceMessageID = "source_message_id"
	// FieldEventType holds the string denoting the event_type field in the database.
	FieldEventType = "event_type"
	// FieldOldValues holds the string denoting the old_values field in the database.
	FieldOldValues = "old_values"
	// FieldNewValues holds the string denoting the new_values field in the database.
	FieldNewValues = "new_values"
	// FieldConfidence holds the string denoting the confidence field in the database.
	FieldConfidence = "confidence"
	// FieldReason holds the string denoting the reason field in the database.
	FieldReason = "reason"
	// EdgeTodo holds the string denoting the todo edge name in mutations.
	EdgeTodo = "todo"
	// EdgeSourceCandidate holds the string denoting the source_candidate edge name in mutations.
	EdgeSourceCandidate = "source_candidate"
	// EdgeSourceMessage holds the string denoting the source_message edge name in mutations.
	EdgeSourceMessage = "source_message"
	// Table holds the table name of the todoevent in the database.
	Table = "todo_events"
	// TodoTable is the table that holds the todo relation/edge.
	TodoTable = "todo_events"
	// TodoInverseTable is the table name for the Todo entity.
	// It exists in this package in order to avoid circular dependency with the "todo" package.
	TodoInverseTable = "todos"
	// TodoColumn is the table column denoting the todo relation/edge.
	TodoColumn = "todo_id"
	// SourceCandidateTable is the table that holds the source_candidate relation/edge.
	SourceCandidateTable = "todo_events"
	// SourceCandidateInverseTable is the table name for the TodoCandidate entity.
	// It exists in this package in order to avoid circular dependency with the "todocandidate" package.
	SourceCandidateInverseTable = "todo_candidates"
	// SourceCandidateColumn is the table column denoting the source_candidate relation/edge.
	SourceCandidateColumn = "source_candidate_id"
	// SourceMessageTable is the table that holds the source_message relation/edge.
	SourceMessageTable = "todo_events"
	// SourceMessageInverseTable is the table name for the ChannelMessage entity.
	// It exists in this package in order to avoid circular dependency with the "channelmessage" package.
	SourceMessageInverseTable = "channel_messages"
	// SourceMessageColumn is the table column denoting the source_message relation/edge.
	SourceMessageColumn = "source_message_id"
)

// Columns holds all SQL columns for todoevent fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldTodoID,
	FieldSourceCandidateID,
	FieldSourceMessageID,
	FieldEventType,
	FieldOldValues,
	FieldNewValues,
	FieldConfidence,
	FieldReason,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultConfidence holds the default value on creation for the "confidence" field.
	DefaultConfidence float64
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// EventType defines the type for the "event_type" enum field.
type EventType string

// EventType values.
const (
	EventTypeCreated   EventType = "created"
	EventTypeUpdated   EventType = "updated"
	EventTypeCancelled EventType = "cancelled"
)

func (et EventType) String() string {
	return string(et)
}

// EventTypeValidator is a validator for the "event_type" field enum values. It is called by the builders before save.
func EventTypeValidator(et EventType) error {
	switch et {
	case EventTypeCreated, EventTypeUpdated, EventTypeCancelled:
		return nil
	default:
		return fmt.Errorf("todoevent: invalid enum value for event_type field: %q", et)
	}
}

// OrderOption defines the ordering options for the TodoEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByTodoID orders the results by the todo_id field.
func ByTodoID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTodoID, opts...).ToFunc()
}

// BySourceCandidateID orders the results by the source_candidate_id field.
func BySourceCandidateID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceCandidateID, opts...).ToFunc()
}

// BySourceMessageID orders the results by the source_message_id field.
func BySourceMessageID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceMessageID, opts...).ToFunc()
}

// ByEventType orders the results by the event_type field.
func ByEventType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventType, opts...).ToFunc()
}

// ByConfidence orders the results by the confidence field.
func ByConfidence(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfidence, opts...).ToFunc()
}

// ByReason orders the results by the reason field.
func ByReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReason, opts...).ToFunc()
}

// ByTodoField orders the results by todo field.
func ByTodoField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTodoStep(), sql.OrderByField(field, opts...))
	}
}

// BySourceCandidateField orders the results by source_candidate field.
func BySourceCandidateField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSourceCandidateStep(), sql.OrderByField(field, opts...))
	}
}

// BySourceMessageField orders the results by source_message field.
func BySourceMessageField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSourceMessageStep(), sql.OrderByField(field, opts...))
	}
}
func newTodoStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TodoInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TodoTable, TodoColumn),
	)
}
func newSourceCandidateStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SourceCandidateInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, SourceCandidateTable, SourceCandidateColumn),
	)
}
func newSourceMessageStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SourceMessageInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, SourceMessageTable, SourceMessageColumn),
	)
}

// MarshalGQL implements graphql.Marshaler interface.
func (e EventType) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *EventType) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = EventType(str)
	if err := EventTypeValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid EventType", str)
	}
	return nil
}
