// Code generated by ent, DO NOT EDIT.

package ent

import (
	"assistant-api/internal/ent/action"
	"assistant-api/internal/ent/skill"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// 技能動作
type Action struct {
	config `json:"-"`
	// ID of the ent.
	// 全域唯一主鍵 UUID
	ID uuid.UUID `json:"id,omitempty"`
	// 所屬 skill
	SkillID uuid.UUID `json:"skill_id,omitempty"`
	// 動作代碼
	ActionCode action.ActionCode `json:"action_code,omitempty"`
	// 動作名稱
	Name string `json:"name,omitempty"`
	// 動作描述
	Description *string `json:"description,omitempty"`
	// API operation 名稱
	APIOperation string `json:"api_operation,omitempty"`
	// 此動作的目的說明，供 AI 理解提問目標
	CommandPurpose *string `json:"command_purpose,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ActionQuery when eager-loading is set.
	Edges        ActionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ActionEdges holds the relations/edges for other nodes in the graph.
type ActionEdges struct {
	// Skill holds the value of the skill edge.
	Skill *Skill `json:"skill,omitempty"`
	// Routes holds the value of the routes edge.
	Routes []*ActionRoute `json:"routes,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
	// totalCount holds the count of the edges above.
	totalCount [2]map[string]int

	namedRoutes map[string][]*ActionRoute
}

// SkillOrErr returns the Skill value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ActionEdges) SkillOrErr() (*Skill, error) {
	if e.Skill != nil {
		return e.Skill, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: skill.Label}
	}
	return nil, &NotLoadedError{edge: "skill"}
}

// RoutesOrErr returns the Routes value or an error if the edge
// was not loaded in eager-loading.
func (e ActionEdges) RoutesOrErr() ([]*ActionRoute, error) {
	if e.loadedTypes[1] {
		return e.Routes, nil
	}
	return nil, &NotLoadedError{edge: "routes"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Action) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case action.FieldActionCode, action.FieldName, action.FieldDescription, action.FieldAPIOperation, action.FieldCommandPurpose:
			values[i] = new(sql.NullString)
		case action.FieldID, action.FieldSkillID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Action fields.
func (_m *Action) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case action.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case action.FieldSkillID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field skill_id", values[i])
			} else if value != nil {
				_m.SkillID = *value
			}
		case action.FieldActionCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action_code", values[i])
			} else if value.Valid {
				_m.ActionCode = action.ActionCode(value.String)
			}
		case action.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case action.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		case action.FieldAPIOperation:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field api_operation", values[i])
			} else if value.Valid {
				_m.APIOperation = value.String
			}
		case action.FieldCommandPurpose:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field command_purpose", values[i])
			} else if value.Valid {
				_m.CommandPurpose = new(string)
				*_m.CommandPurpose = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Action.
// This includes values selected through modifiers, order, etc.
func (_m *Action) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySkill queries the "skill" edge of the Action entity.
func (_m *Action) QuerySkill() *SkillQuery {
	return NewActionClient(_m.config).QuerySkill(_m)
}

// QueryRoutes queries the "routes" edge of the Action entity.
func (_m *Action) QueryRoutes() *ActionRouteQuery {
	return NewActionClient(_m.config).QueryRoutes(_m)
}

// Update returns a builder for updating this Action.
// Note that you need to call Action.Unwrap() before calling this method if this Action
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Action) Update() *ActionUpdateOne {
	return NewActionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Action entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Action) Unwrap() *Action {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Action is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Action) String() string {
	var builder strings.Builder
	builder.WriteString("Action(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("skill_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SkillID))
	builder.WriteString(", ")
	builder.WriteString("action_code=")
	builder.WriteString(fmt.Sprintf("%v", _m.ActionCode))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("api_operation=")
	builder.WriteString(_m.APIOperation)
	builder.WriteString(", ")
	if v := _m.CommandPurpose; v != nil {
		builder.WriteString("command_purpose=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// NamedRoutes returns the Routes named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Action) NamedRoutes(name string) ([]*ActionRoute, error) {
	if _m.Edges.namedRoutes == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedRoutes[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Action) appendNamedRoutes(name string, edges ...*ActionRoute) {
	if _m.Edges.namedRoutes == nil {
		_m.Edges.namedRoutes = make(map[string][]*ActionRoute)
	}
	if len(edges) == 0 {
		_m.Edges.namedRoutes[name] = []*ActionRoute{}
	} else {
		_m.Edges.namedRoutes[name] = append(_m.Edges.namedRoutes[name], edges...)
	}
}

// Actions is a parsable slice of Action.
type Actions []*Action
