// Code generated by ent, DO NOT EDIT.

package ent

import (
	"assistant-api/internal/ent/channel"
	"assistant-api/internal/ent/channelmessage"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ChannelMessageCreate is the builder for creating a ChannelMessage entity.
type ChannelMessageCreate struct {
	config
	mutation *ChannelMessageMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *ChannelMessageCreate) SetCreatedAt(v time.Time) *ChannelMessageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ChannelMessageCreate) SetNillableCreatedAt(v *time.Time) *ChannelMessageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ChannelMessageCreate) SetUpdatedAt(v time.Time) *ChannelMessageCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ChannelMessageCreate) SetNillableUpdatedAt(v *time.Time) *ChannelMessageCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetContent sets the "content" field.
func (_c *ChannelMessageCreate) SetContent(v string) *ChannelMessageCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetChannelID sets the "channel_id" field.
func (_c *ChannelMessageCreate) SetChannelID(v uuid.UUID) *ChannelMessageCreate {
	_c.mutation.SetChannelID(v)
	return _c
}

// SetRelatedMessageID sets the "related_message_id" field.
func (_c *ChannelMessageCreate) SetRelatedMessageID(v uuid.UUID) *ChannelMessageCreate {
	_c.mutation.SetRelatedMessageID(v)
	return _c
}

// SetNillableRelatedMessageID sets the "related_message_id" field if the given value is not nil.
func (_c *ChannelMessageCreate) SetNillableRelatedMessageID(v *uuid.UUID) *ChannelMessageCreate {
	if v != nil {
		_c.SetRelatedMessageID(*v)
	}
	return _c
}

// SetSenderID sets the "sender_id" field.
func (_c *ChannelMessageCreate) SetSenderID(v string) *ChannelMessageCreate {
	_c.mutation.SetSenderID(v)
	return _c
}

// SetSenderName sets the "sender_name" field.
func (_c *ChannelMessageCreate) SetSenderName(v string) *ChannelMessageCreate {
	_c.mutation.SetSenderName(v)
	return _c
}

// SetNillableSenderName sets the "sender_name" field if the given value is not nil.
func (_c *ChannelMessageCreate) SetNillableSenderName(v *string) *ChannelMessageCreate {
	if v != nil {
		_c.SetSenderName(*v)
	}
	return _c
}

// SetPlatformMessageID sets the "platform_message_id" field.
func (_c *ChannelMessageCreate) SetPlatformMessageID(v string) *ChannelMessageCreate {
	_c.mutation.SetPlatformMessageID(v)
	return _c
}

// SetNillablePlatformMessageID sets the "platform_message_id" field if the given value is not nil.
func (_c *ChannelMessageCreate) SetNillablePlatformMessageID(v *string) *ChannelMessageCreate {
	if v != nil {
		_c.SetPlatformMessageID(*v)
	}
	return _c
}

// SetReplyToMsgID sets the "reply_to_msg_id" field.
func (_c *ChannelMessageCreate) SetReplyToMsgID(v string) *ChannelMessageCreate {
	_c.mutation.SetReplyToMsgID(v)
	return _c
}

// SetNillableReplyToMsgID sets the "reply_to_msg_id" field if the given value is not nil.
func (_c *ChannelMessageCreate) SetNillableReplyToMsgID(v *string) *ChannelMessageCreate {
	if v != nil {
		_c.SetReplyToMsgID(*v)
	}
	return _c
}

// SetMessageType sets the "message_type" field.
func (_c *ChannelMessageCreate) SetMessageType(v string) *ChannelMessageCreate {
	_c.mutation.SetMessageType(v)
	return _c
}

// SetNillableMessageType sets the "message_type" field if the given value is not nil.
func (_c *ChannelMessageCreate) SetNillableMessageType(v *string) *ChannelMessageCreate {
	if v != nil {
		_c.SetMessageType(*v)
	}
	return _c
}

// SetPlatformTimestamp sets the "platform_timestamp" field.
func (_c *ChannelMessageCreate) SetPlatformTimestamp(v int64) *ChannelMessageCreate {
	_c.mutation.SetPlatformTimestamp(v)
	return _c
}

// SetNillablePlatformTimestamp sets the "platform_timestamp" field if the given value is not nil.
func (_c *ChannelMessageCreate) SetNillablePlatformTimestamp(v *int64) *ChannelMessageCreate {
	if v != nil {
		_c.SetPlatformTimestamp(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ChannelMessageCreate) SetID(v uuid.UUID) *ChannelMessageCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ChannelMessageCreate) SetNillableID(v *uuid.UUID) *ChannelMessageCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_c *ChannelMessageCreate) SetChannel(v *Channel) *ChannelMessageCreate {
	return _c.SetChannelID(v.ID)
}

// SetRelatedMessage sets the "related_message" edge to the ChannelMessage entity.
func (_c *ChannelMessageCreate) SetRelatedMessage(v *ChannelMessage) *ChannelMessageCreate {
	return _c.SetRelatedMessageID(v.ID)
}

// AddReplyIDs adds the "replies" edge to the ChannelMessage entity by IDs.
func (_c *ChannelMessageCreate) AddReplyIDs(ids ...uuid.UUID) *ChannelMessageCreate {
	_c.mutation.AddReplyIDs(ids...)
	return _c
}

// AddReplies adds the "replies" edges to the ChannelMessage entity.
func (_c *ChannelMessageCreate) AddReplies(v ...*ChannelMessage) *ChannelMessageCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddReplyIDs(ids...)
}

// Mutation returns the ChannelMessageMutation object of the builder.
func (_c *ChannelMessageCreate) Mutation() *ChannelMessageMutation {
	return _c.mutation
}

// Save creates the ChannelMessage in the database.
func (_c *ChannelMessageCreate) Save(ctx context.Context) (*ChannelMessage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChannelMessageCreate) SaveX(ctx context.Context) *ChannelMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChannelMessageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChannelMessageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChannelMessageCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := channelmessage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := channelmessage.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.MessageType(); !ok {
		v := channelmessage.DefaultMessageType
		_c.mutation.SetMessageType(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := channelmessage.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChannelMessageCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ChannelMessage.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ChannelMessage.updated_at"`)}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "ChannelMessage.content"`)}
	}
	if v, ok := _c.mutation.Content(); ok {
		if err := channelmessage.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "ChannelMessage.content": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ChannelID(); !ok {
		return &ValidationError{Name: "channel_id", err: errors.New(`ent: missing required field "ChannelMessage.channel_id"`)}
	}
	if _, ok := _c.mutation.SenderID(); !ok {
		return &ValidationError{Name: "sender_id", err: errors.New(`ent: missing required field "ChannelMessage.sender_id"`)}
	}
	if _, ok := _c.mutation.MessageType(); !ok {
		return &ValidationError{Name: "message_type", err: errors.New(`ent: missing required field "ChannelMessage.message_type"`)}
	}
	if len(_c.mutation.ChannelIDs()) == 0 {
		return &ValidationError{Name: "channel", err: errors.New(`ent: missing required edge "ChannelMessage.channel"`)}
	}
	return nil
}

func (_c *ChannelMessageCreate) sqlSave(ctx context.Context) (*ChannelMessage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChannelMessageCreate) createSpec() (*ChannelMessage, *sqlgraph.CreateSpec) {
	var (
		_node = &ChannelMessage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(channelmessage.Table, sqlgraph.NewFieldSpec(channelmessage.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(channelmessage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(channelmessage.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(channelmessage.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.SenderID(); ok {
		_spec.SetField(channelmessage.FieldSenderID, field.TypeString, value)
		_node.SenderID = value
	}
	if value, ok := _c.mutation.SenderName(); ok {
		_spec.SetField(channelmessage.FieldSenderName, field.TypeString, value)
		_node.SenderName = value
	}
	if value, ok := _c.mutation.PlatformMessageID(); ok {
		_spec.SetField(channelmessage.FieldPlatformMessageID, field.TypeString, value)
		_node.PlatformMessageID = value
	}
	if value, ok := _c.mutation.ReplyToMsgID(); ok {
		_spec.SetField(channelmessage.FieldReplyToMsgID, field.TypeString, value)
		_node.ReplyToMsgID = value
	}
	if value, ok := _c.mutation.MessageType(); ok {
		_spec.SetField(channelmessage.FieldMessageType, field.TypeString, value)
		_node.MessageType = value
	}
	if value, ok := _c.mutation.PlatformTimestamp(); ok {
		_spec.SetField(channelmessage.FieldPlatformTimestamp, field.TypeInt64, value)
		_node.PlatformTimestamp = value
	}
	if nodes := _c.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelmessage.ChannelTable,
			Columns: []string{channelmessage.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ChannelID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RelatedMessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   channelmessage.RelatedMessageTable,
			Columns: []string{channelmessage.RelatedMessageColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelmessage.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RelatedMessageID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RepliesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   channelmessage.RepliesTable,
			Columns: []string{channelmessage.RepliesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelmessage.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ChannelMessageCreateBulk is the builder for creating many ChannelMessage entities in bulk.
type ChannelMessageCreateBulk struct {
	config
	err      error
	builders []*ChannelMessageCreate
}

// Save creates the ChannelMessage entities in the database.
func (_c *ChannelMessageCreateBulk) Save(ctx context.Context) ([]*ChannelMessage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ChannelMessage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChannelMessageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChannelMessageCreateBulk) SaveX(ctx context.Context) []*ChannelMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChannelMessageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChannelMessageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
