// Code generated by ent, DO NOT EDIT.

package ent

import (
	"assistant-api/internal/ent/channelmessage"
	"assistant-api/internal/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ChannelMessageUpdate is the builder for updating ChannelMessage entities.
type ChannelMessageUpdate struct {
	config
	hooks    []Hook
	mutation *ChannelMessageMutation
}

// Where appends a list predicates to the ChannelMessageUpdate builder.
func (_u *ChannelMessageUpdate) Where(ps ...predicate.ChannelMessage) *ChannelMessageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChannelMessageUpdate) SetUpdatedAt(v time.Time) *ChannelMessageUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetContent sets the "content" field.
func (_u *ChannelMessageUpdate) SetContent(v string) *ChannelMessageUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *ChannelMessageUpdate) SetNillableContent(v *string) *ChannelMessageUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetTriggeredMessageID sets the "triggered_message_id" field.
// 中文說明：更新系統訊息來源時寫入內部訊息 ID，和平台 reply_to_msg_id 保持不同語意。
func (_u *ChannelMessageUpdate) SetTriggeredMessageID(v uuid.UUID) *ChannelMessageUpdate {
	_u.mutation.SetTriggeredMessageID(v)
	return _u
}

// SetNillableTriggeredMessageID sets the "triggered_message_id" field if the given value is not nil.
// 中文說明：nil 代表不變更來源關聯，避免更新流程意外清空既有觸發來源。
func (_u *ChannelMessageUpdate) SetNillableTriggeredMessageID(v *uuid.UUID) *ChannelMessageUpdate {
	if v != nil {
		_u.SetTriggeredMessageID(*v)
	}
	return _u
}

// ClearTriggeredMessageID clears the value of the "triggered_message_id" field.
// 中文說明：只有確認系統訊息不應再連回來源訊息時才清除此欄位。
func (_u *ChannelMessageUpdate) ClearTriggeredMessageID() *ChannelMessageUpdate {
	_u.mutation.ClearTriggeredMessageID()
	return _u
}

// SetPlatformTenantID sets the "platform_tenant_id" field.
func (_u *ChannelMessageUpdate) SetPlatformTenantID(v string) *ChannelMessageUpdate {
	_u.mutation.SetPlatformTenantID(v)
	return _u
}

// SetNillablePlatformTenantID sets the "platform_tenant_id" field if the given value is not nil.
func (_u *ChannelMessageUpdate) SetNillablePlatformTenantID(v *string) *ChannelMessageUpdate {
	if v != nil {
		_u.SetPlatformTenantID(*v)
	}
	return _u
}

// ClearPlatformTenantID clears the value of the "platform_tenant_id" field.
func (_u *ChannelMessageUpdate) ClearPlatformTenantID() *ChannelMessageUpdate {
	_u.mutation.ClearPlatformTenantID()
	return _u
}

// SetSenderID sets the "sender_id" field.
func (_u *ChannelMessageUpdate) SetSenderID(v string) *ChannelMessageUpdate {
	_u.mutation.SetSenderID(v)
	return _u
}

// SetNillableSenderID sets the "sender_id" field if the given value is not nil.
func (_u *ChannelMessageUpdate) SetNillableSenderID(v *string) *ChannelMessageUpdate {
	if v != nil {
		_u.SetSenderID(*v)
	}
	return _u
}

// SetSenderUserID sets the "sender_user_id" field.
func (_u *ChannelMessageUpdate) SetSenderUserID(v uuid.UUID) *ChannelMessageUpdate {
	_u.mutation.SetSenderUserID(v)
	return _u
}

// SetNillableSenderUserID sets the "sender_user_id" field if the given value is not nil.
func (_u *ChannelMessageUpdate) SetNillableSenderUserID(v *uuid.UUID) *ChannelMessageUpdate {
	if v != nil {
		_u.SetSenderUserID(*v)
	}
	return _u
}

// ClearSenderUserID clears the value of the "sender_user_id" field.
func (_u *ChannelMessageUpdate) ClearSenderUserID() *ChannelMessageUpdate {
	_u.mutation.ClearSenderUserID()
	return _u
}

// SetSenderName sets the "sender_name" field.
func (_u *ChannelMessageUpdate) SetSenderName(v string) *ChannelMessageUpdate {
	_u.mutation.SetSenderName(v)
	return _u
}

// SetNillableSenderName sets the "sender_name" field if the given value is not nil.
func (_u *ChannelMessageUpdate) SetNillableSenderName(v *string) *ChannelMessageUpdate {
	if v != nil {
		_u.SetSenderName(*v)
	}
	return _u
}

// ClearSenderName clears the value of the "sender_name" field.
func (_u *ChannelMessageUpdate) ClearSenderName() *ChannelMessageUpdate {
	_u.mutation.ClearSenderName()
	return _u
}

// SetPlatformMessageID sets the "platform_message_id" field.
func (_u *ChannelMessageUpdate) SetPlatformMessageID(v string) *ChannelMessageUpdate {
	_u.mutation.SetPlatformMessageID(v)
	return _u
}

// SetNillablePlatformMessageID sets the "platform_message_id" field if the given value is not nil.
func (_u *ChannelMessageUpdate) SetNillablePlatformMessageID(v *string) *ChannelMessageUpdate {
	if v != nil {
		_u.SetPlatformMessageID(*v)
	}
	return _u
}

// ClearPlatformMessageID clears the value of the "platform_message_id" field.
func (_u *ChannelMessageUpdate) ClearPlatformMessageID() *ChannelMessageUpdate {
	_u.mutation.ClearPlatformMessageID()
	return _u
}

// SetReplyToMsgID sets the "reply_to_msg_id" field.
func (_u *ChannelMessageUpdate) SetReplyToMsgID(v string) *ChannelMessageUpdate {
	_u.mutation.SetReplyToMsgID(v)
	return _u
}

// SetNillableReplyToMsgID sets the "reply_to_msg_id" field if the given value is not nil.
func (_u *ChannelMessageUpdate) SetNillableReplyToMsgID(v *string) *ChannelMessageUpdate {
	if v != nil {
		_u.SetReplyToMsgID(*v)
	}
	return _u
}

// ClearReplyToMsgID clears the value of the "reply_to_msg_id" field.
func (_u *ChannelMessageUpdate) ClearReplyToMsgID() *ChannelMessageUpdate {
	_u.mutation.ClearReplyToMsgID()
	return _u
}

// SetMessageType sets the "message_type" field.
func (_u *ChannelMessageUpdate) SetMessageType(v string) *ChannelMessageUpdate {
	_u.mutation.SetMessageType(v)
	return _u
}

// SetNillableMessageType sets the "message_type" field if the given value is not nil.
func (_u *ChannelMessageUpdate) SetNillableMessageType(v *string) *ChannelMessageUpdate {
	if v != nil {
		_u.SetMessageType(*v)
	}
	return _u
}

// SetPlatformTimestamp sets the "platform_timestamp" field.
func (_u *ChannelMessageUpdate) SetPlatformTimestamp(v int64) *ChannelMessageUpdate {
	_u.mutation.ResetPlatformTimestamp()
	_u.mutation.SetPlatformTimestamp(v)
	return _u
}

// SetNillablePlatformTimestamp sets the "platform_timestamp" field if the given value is not nil.
func (_u *ChannelMessageUpdate) SetNillablePlatformTimestamp(v *int64) *ChannelMessageUpdate {
	if v != nil {
		_u.SetPlatformTimestamp(*v)
	}
	return _u
}

// AddPlatformTimestamp adds value to the "platform_timestamp" field.
func (_u *ChannelMessageUpdate) AddPlatformTimestamp(v int64) *ChannelMessageUpdate {
	_u.mutation.AddPlatformTimestamp(v)
	return _u
}

// ClearPlatformTimestamp clears the value of the "platform_timestamp" field.
func (_u *ChannelMessageUpdate) ClearPlatformTimestamp() *ChannelMessageUpdate {
	_u.mutation.ClearPlatformTimestamp()
	return _u
}

// SetTriggeredMessage sets the "triggered_message" edge to the ChannelMessage entity.
// 中文說明：以 edge 形式設定來源訊息，底層仍會落到 triggered_message_id 欄位。
func (_u *ChannelMessageUpdate) SetTriggeredMessage(v *ChannelMessage) *ChannelMessageUpdate {
	return _u.SetTriggeredMessageID(v.ID)
}

// AddTriggeredMessageIDs adds the "triggered_messages" edge to the ChannelMessage entity by IDs.
// 中文說明：將多筆系統輸出掛回目前訊息，建立來源訊息到系統訊息的一對多關係。
func (_u *ChannelMessageUpdate) AddTriggeredMessageIDs(ids ...uuid.UUID) *ChannelMessageUpdate {
	_u.mutation.AddTriggeredMessageIDs(ids...)
	return _u
}

// AddTriggeredMessages adds the "triggered_messages" edges to the ChannelMessage entity.
func (_u *ChannelMessageUpdate) AddTriggeredMessages(v ...*ChannelMessage) *ChannelMessageUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTriggeredMessageIDs(ids...)
}

// Mutation returns the ChannelMessageMutation object of the builder.
func (_u *ChannelMessageUpdate) Mutation() *ChannelMessageMutation {
	return _u.mutation
}

// ClearTriggeredMessage clears the "triggered_message" edge to the ChannelMessage entity.
// 中文說明：清除本訊息指向來源訊息的內部觸發 edge。
func (_u *ChannelMessageUpdate) ClearTriggeredMessage() *ChannelMessageUpdate {
	_u.mutation.ClearTriggeredMessage()
	return _u
}

// ClearTriggeredMessages clears all "triggered_messages" edges to the ChannelMessage entity.
// 中文說明：移除所有由目前訊息觸發出的系統訊息反向關聯。
func (_u *ChannelMessageUpdate) ClearTriggeredMessages() *ChannelMessageUpdate {
	_u.mutation.ClearTriggeredMessages()
	return _u
}

// RemoveTriggeredMessageIDs removes the "triggered_messages" edge to ChannelMessage entities by IDs.
func (_u *ChannelMessageUpdate) RemoveTriggeredMessageIDs(ids ...uuid.UUID) *ChannelMessageUpdate {
	_u.mutation.RemoveTriggeredMessageIDs(ids...)
	return _u
}

// RemoveTriggeredMessages removes "triggered_messages" edges to ChannelMessage entities.
func (_u *ChannelMessageUpdate) RemoveTriggeredMessages(v ...*ChannelMessage) *ChannelMessageUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTriggeredMessageIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChannelMessageUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChannelMessageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChannelMessageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChannelMessageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChannelMessageUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := channelmessage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChannelMessageUpdate) check() error {
	if v, ok := _u.mutation.Content(); ok {
		if err := channelmessage.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "ChannelMessage.content": %w`, err)}
		}
	}
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChannelMessage.channel"`)
	}
	return nil
}

func (_u *ChannelMessageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(channelmessage.Table, channelmessage.Columns, sqlgraph.NewFieldSpec(channelmessage.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(channelmessage.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(channelmessage.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlatformTenantID(); ok {
		_spec.SetField(channelmessage.FieldPlatformTenantID, field.TypeString, value)
	}
	if _u.mutation.PlatformTenantIDCleared() {
		_spec.ClearField(channelmessage.FieldPlatformTenantID, field.TypeString)
	}
	if value, ok := _u.mutation.SenderID(); ok {
		_spec.SetField(channelmessage.FieldSenderID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SenderUserID(); ok {
		_spec.SetField(channelmessage.FieldSenderUserID, field.TypeUUID, value)
	}
	if _u.mutation.SenderUserIDCleared() {
		_spec.ClearField(channelmessage.FieldSenderUserID, field.TypeUUID)
	}
	if value, ok := _u.mutation.SenderName(); ok {
		_spec.SetField(channelmessage.FieldSenderName, field.TypeString, value)
	}
	if _u.mutation.SenderNameCleared() {
		_spec.ClearField(channelmessage.FieldSenderName, field.TypeString)
	}
	if value, ok := _u.mutation.PlatformMessageID(); ok {
		_spec.SetField(channelmessage.FieldPlatformMessageID, field.TypeString, value)
	}
	if _u.mutation.PlatformMessageIDCleared() {
		_spec.ClearField(channelmessage.FieldPlatformMessageID, field.TypeString)
	}
	if value, ok := _u.mutation.ReplyToMsgID(); ok {
		_spec.SetField(channelmessage.FieldReplyToMsgID, field.TypeString, value)
	}
	if _u.mutation.ReplyToMsgIDCleared() {
		_spec.ClearField(channelmessage.FieldReplyToMsgID, field.TypeString)
	}
	if value, ok := _u.mutation.MessageType(); ok {
		_spec.SetField(channelmessage.FieldMessageType, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlatformTimestamp(); ok {
		_spec.SetField(channelmessage.FieldPlatformTimestamp, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPlatformTimestamp(); ok {
		_spec.AddField(channelmessage.FieldPlatformTimestamp, field.TypeInt64, value)
	}
	if _u.mutation.PlatformTimestampCleared() {
		_spec.ClearField(channelmessage.FieldPlatformTimestamp, field.TypeInt64)
	}
	if _u.mutation.TriggeredMessageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   channelmessage.TriggeredMessageTable,
			Columns: []string{channelmessage.TriggeredMessageColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelmessage.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TriggeredMessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   channelmessage.TriggeredMessageTable,
			Columns: []string{channelmessage.TriggeredMessageColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelmessage.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TriggeredMessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   channelmessage.TriggeredMessagesTable,
			Columns: []string{channelmessage.TriggeredMessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelmessage.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTriggeredMessagesIDs(); len(nodes) > 0 && !_u.mutation.TriggeredMessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   channelmessage.TriggeredMessagesTable,
			Columns: []string{channelmessage.TriggeredMessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelmessage.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TriggeredMessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   channelmessage.TriggeredMessagesTable,
			Columns: []string{channelmessage.TriggeredMessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelmessage.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{channelmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChannelMessageUpdateOne is the builder for updating a single ChannelMessage entity.
type ChannelMessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChannelMessageMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChannelMessageUpdateOne) SetUpdatedAt(v time.Time) *ChannelMessageUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetContent sets the "content" field.
func (_u *ChannelMessageUpdateOne) SetContent(v string) *ChannelMessageUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *ChannelMessageUpdateOne) SetNillableContent(v *string) *ChannelMessageUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetTriggeredMessageID sets the "triggered_message_id" field.
func (_u *ChannelMessageUpdateOne) SetTriggeredMessageID(v uuid.UUID) *ChannelMessageUpdateOne {
	_u.mutation.SetTriggeredMessageID(v)
	return _u
}

// SetNillableTriggeredMessageID sets the "triggered_message_id" field if the given value is not nil.
func (_u *ChannelMessageUpdateOne) SetNillableTriggeredMessageID(v *uuid.UUID) *ChannelMessageUpdateOne {
	if v != nil {
		_u.SetTriggeredMessageID(*v)
	}
	return _u
}

// ClearTriggeredMessageID clears the value of the "triggered_message_id" field.
func (_u *ChannelMessageUpdateOne) ClearTriggeredMessageID() *ChannelMessageUpdateOne {
	_u.mutation.ClearTriggeredMessageID()
	return _u
}

// SetPlatformTenantID sets the "platform_tenant_id" field.
func (_u *ChannelMessageUpdateOne) SetPlatformTenantID(v string) *ChannelMessageUpdateOne {
	_u.mutation.SetPlatformTenantID(v)
	return _u
}

// SetNillablePlatformTenantID sets the "platform_tenant_id" field if the given value is not nil.
func (_u *ChannelMessageUpdateOne) SetNillablePlatformTenantID(v *string) *ChannelMessageUpdateOne {
	if v != nil {
		_u.SetPlatformTenantID(*v)
	}
	return _u
}

// ClearPlatformTenantID clears the value of the "platform_tenant_id" field.
func (_u *ChannelMessageUpdateOne) ClearPlatformTenantID() *ChannelMessageUpdateOne {
	_u.mutation.ClearPlatformTenantID()
	return _u
}

// SetSenderID sets the "sender_id" field.
func (_u *ChannelMessageUpdateOne) SetSenderID(v string) *ChannelMessageUpdateOne {
	_u.mutation.SetSenderID(v)
	return _u
}

// SetNillableSenderID sets the "sender_id" field if the given value is not nil.
func (_u *ChannelMessageUpdateOne) SetNillableSenderID(v *string) *ChannelMessageUpdateOne {
	if v != nil {
		_u.SetSenderID(*v)
	}
	return _u
}

// SetSenderUserID sets the "sender_user_id" field.
func (_u *ChannelMessageUpdateOne) SetSenderUserID(v uuid.UUID) *ChannelMessageUpdateOne {
	_u.mutation.SetSenderUserID(v)
	return _u
}

// SetNillableSenderUserID sets the "sender_user_id" field if the given value is not nil.
func (_u *ChannelMessageUpdateOne) SetNillableSenderUserID(v *uuid.UUID) *ChannelMessageUpdateOne {
	if v != nil {
		_u.SetSenderUserID(*v)
	}
	return _u
}

// ClearSenderUserID clears the value of the "sender_user_id" field.
func (_u *ChannelMessageUpdateOne) ClearSenderUserID() *ChannelMessageUpdateOne {
	_u.mutation.ClearSenderUserID()
	return _u
}

// SetSenderName sets the "sender_name" field.
func (_u *ChannelMessageUpdateOne) SetSenderName(v string) *ChannelMessageUpdateOne {
	_u.mutation.SetSenderName(v)
	return _u
}

// SetNillableSenderName sets the "sender_name" field if the given value is not nil.
func (_u *ChannelMessageUpdateOne) SetNillableSenderName(v *string) *ChannelMessageUpdateOne {
	if v != nil {
		_u.SetSenderName(*v)
	}
	return _u
}

// ClearSenderName clears the value of the "sender_name" field.
func (_u *ChannelMessageUpdateOne) ClearSenderName() *ChannelMessageUpdateOne {
	_u.mutation.ClearSenderName()
	return _u
}

// SetPlatformMessageID sets the "platform_message_id" field.
func (_u *ChannelMessageUpdateOne) SetPlatformMessageID(v string) *ChannelMessageUpdateOne {
	_u.mutation.SetPlatformMessageID(v)
	return _u
}

// SetNillablePlatformMessageID sets the "platform_message_id" field if the given value is not nil.
func (_u *ChannelMessageUpdateOne) SetNillablePlatformMessageID(v *string) *ChannelMessageUpdateOne {
	if v != nil {
		_u.SetPlatformMessageID(*v)
	}
	return _u
}

// ClearPlatformMessageID clears the value of the "platform_message_id" field.
func (_u *ChannelMessageUpdateOne) ClearPlatformMessageID() *ChannelMessageUpdateOne {
	_u.mutation.ClearPlatformMessageID()
	return _u
}

// SetReplyToMsgID sets the "reply_to_msg_id" field.
func (_u *ChannelMessageUpdateOne) SetReplyToMsgID(v string) *ChannelMessageUpdateOne {
	_u.mutation.SetReplyToMsgID(v)
	return _u
}

// SetNillableReplyToMsgID sets the "reply_to_msg_id" field if the given value is not nil.
func (_u *ChannelMessageUpdateOne) SetNillableReplyToMsgID(v *string) *ChannelMessageUpdateOne {
	if v != nil {
		_u.SetReplyToMsgID(*v)
	}
	return _u
}

// ClearReplyToMsgID clears the value of the "reply_to_msg_id" field.
func (_u *ChannelMessageUpdateOne) ClearReplyToMsgID() *ChannelMessageUpdateOne {
	_u.mutation.ClearReplyToMsgID()
	return _u
}

// SetMessageType sets the "message_type" field.
func (_u *ChannelMessageUpdateOne) SetMessageType(v string) *ChannelMessageUpdateOne {
	_u.mutation.SetMessageType(v)
	return _u
}

// SetNillableMessageType sets the "message_type" field if the given value is not nil.
func (_u *ChannelMessageUpdateOne) SetNillableMessageType(v *string) *ChannelMessageUpdateOne {
	if v != nil {
		_u.SetMessageType(*v)
	}
	return _u
}

// SetPlatformTimestamp sets the "platform_timestamp" field.
func (_u *ChannelMessageUpdateOne) SetPlatformTimestamp(v int64) *ChannelMessageUpdateOne {
	_u.mutation.ResetPlatformTimestamp()
	_u.mutation.SetPlatformTimestamp(v)
	return _u
}

// SetNillablePlatformTimestamp sets the "platform_timestamp" field if the given value is not nil.
func (_u *ChannelMessageUpdateOne) SetNillablePlatformTimestamp(v *int64) *ChannelMessageUpdateOne {
	if v != nil {
		_u.SetPlatformTimestamp(*v)
	}
	return _u
}

// AddPlatformTimestamp adds value to the "platform_timestamp" field.
func (_u *ChannelMessageUpdateOne) AddPlatformTimestamp(v int64) *ChannelMessageUpdateOne {
	_u.mutation.AddPlatformTimestamp(v)
	return _u
}

// ClearPlatformTimestamp clears the value of the "platform_timestamp" field.
func (_u *ChannelMessageUpdateOne) ClearPlatformTimestamp() *ChannelMessageUpdateOne {
	_u.mutation.ClearPlatformTimestamp()
	return _u
}

// SetTriggeredMessage sets the "triggered_message" edge to the ChannelMessage entity.
func (_u *ChannelMessageUpdateOne) SetTriggeredMessage(v *ChannelMessage) *ChannelMessageUpdateOne {
	return _u.SetTriggeredMessageID(v.ID)
}

// AddTriggeredMessageIDs adds the "triggered_messages" edge to the ChannelMessage entity by IDs.
func (_u *ChannelMessageUpdateOne) AddTriggeredMessageIDs(ids ...uuid.UUID) *ChannelMessageUpdateOne {
	_u.mutation.AddTriggeredMessageIDs(ids...)
	return _u
}

// AddTriggeredMessages adds the "triggered_messages" edges to the ChannelMessage entity.
func (_u *ChannelMessageUpdateOne) AddTriggeredMessages(v ...*ChannelMessage) *ChannelMessageUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTriggeredMessageIDs(ids...)
}

// Mutation returns the ChannelMessageMutation object of the builder.
func (_u *ChannelMessageUpdateOne) Mutation() *ChannelMessageMutation {
	return _u.mutation
}

// ClearTriggeredMessage clears the "triggered_message" edge to the ChannelMessage entity.
func (_u *ChannelMessageUpdateOne) ClearTriggeredMessage() *ChannelMessageUpdateOne {
	_u.mutation.ClearTriggeredMessage()
	return _u
}

// ClearTriggeredMessages clears all "triggered_messages" edges to the ChannelMessage entity.
func (_u *ChannelMessageUpdateOne) ClearTriggeredMessages() *ChannelMessageUpdateOne {
	_u.mutation.ClearTriggeredMessages()
	return _u
}

// RemoveTriggeredMessageIDs removes the "triggered_messages" edge to ChannelMessage entities by IDs.
func (_u *ChannelMessageUpdateOne) RemoveTriggeredMessageIDs(ids ...uuid.UUID) *ChannelMessageUpdateOne {
	_u.mutation.RemoveTriggeredMessageIDs(ids...)
	return _u
}

// RemoveTriggeredMessages removes "triggered_messages" edges to ChannelMessage entities.
func (_u *ChannelMessageUpdateOne) RemoveTriggeredMessages(v ...*ChannelMessage) *ChannelMessageUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTriggeredMessageIDs(ids...)
}

// Where appends a list predicates to the ChannelMessageUpdate builder.
func (_u *ChannelMessageUpdateOne) Where(ps ...predicate.ChannelMessage) *ChannelMessageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChannelMessageUpdateOne) Select(field string, fields ...string) *ChannelMessageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ChannelMessage entity.
func (_u *ChannelMessageUpdateOne) Save(ctx context.Context) (*ChannelMessage, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChannelMessageUpdateOne) SaveX(ctx context.Context) *ChannelMessage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChannelMessageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChannelMessageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChannelMessageUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := channelmessage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChannelMessageUpdateOne) check() error {
	if v, ok := _u.mutation.Content(); ok {
		if err := channelmessage.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "ChannelMessage.content": %w`, err)}
		}
	}
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChannelMessage.channel"`)
	}
	return nil
}

func (_u *ChannelMessageUpdateOne) sqlSave(ctx context.Context) (_node *ChannelMessage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(channelmessage.Table, channelmessage.Columns, sqlgraph.NewFieldSpec(channelmessage.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ChannelMessage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, channelmessage.FieldID)
		for _, f := range fields {
			if !channelmessage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != channelmessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(channelmessage.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(channelmessage.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlatformTenantID(); ok {
		_spec.SetField(channelmessage.FieldPlatformTenantID, field.TypeString, value)
	}
	if _u.mutation.PlatformTenantIDCleared() {
		_spec.ClearField(channelmessage.FieldPlatformTenantID, field.TypeString)
	}
	if value, ok := _u.mutation.SenderID(); ok {
		_spec.SetField(channelmessage.FieldSenderID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SenderUserID(); ok {
		_spec.SetField(channelmessage.FieldSenderUserID, field.TypeUUID, value)
	}
	if _u.mutation.SenderUserIDCleared() {
		_spec.ClearField(channelmessage.FieldSenderUserID, field.TypeUUID)
	}
	if value, ok := _u.mutation.SenderName(); ok {
		_spec.SetField(channelmessage.FieldSenderName, field.TypeString, value)
	}
	if _u.mutation.SenderNameCleared() {
		_spec.ClearField(channelmessage.FieldSenderName, field.TypeString)
	}
	if value, ok := _u.mutation.PlatformMessageID(); ok {
		_spec.SetField(channelmessage.FieldPlatformMessageID, field.TypeString, value)
	}
	if _u.mutation.PlatformMessageIDCleared() {
		_spec.ClearField(channelmessage.FieldPlatformMessageID, field.TypeString)
	}
	if value, ok := _u.mutation.ReplyToMsgID(); ok {
		_spec.SetField(channelmessage.FieldReplyToMsgID, field.TypeString, value)
	}
	if _u.mutation.ReplyToMsgIDCleared() {
		_spec.ClearField(channelmessage.FieldReplyToMsgID, field.TypeString)
	}
	if value, ok := _u.mutation.MessageType(); ok {
		_spec.SetField(channelmessage.FieldMessageType, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlatformTimestamp(); ok {
		_spec.SetField(channelmessage.FieldPlatformTimestamp, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPlatformTimestamp(); ok {
		_spec.AddField(channelmessage.FieldPlatformTimestamp, field.TypeInt64, value)
	}
	if _u.mutation.PlatformTimestampCleared() {
		_spec.ClearField(channelmessage.FieldPlatformTimestamp, field.TypeInt64)
	}
	if _u.mutation.TriggeredMessageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   channelmessage.TriggeredMessageTable,
			Columns: []string{channelmessage.TriggeredMessageColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelmessage.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TriggeredMessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   channelmessage.TriggeredMessageTable,
			Columns: []string{channelmessage.TriggeredMessageColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelmessage.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TriggeredMessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   channelmessage.TriggeredMessagesTable,
			Columns: []string{channelmessage.TriggeredMessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelmessage.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTriggeredMessagesIDs(); len(nodes) > 0 && !_u.mutation.TriggeredMessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   channelmessage.TriggeredMessagesTable,
			Columns: []string{channelmessage.TriggeredMessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelmessage.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TriggeredMessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   channelmessage.TriggeredMessagesTable,
			Columns: []string{channelmessage.TriggeredMessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelmessage.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ChannelMessage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{channelmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
