// Code generated by ent, DO NOT EDIT.

package ent

import (
	"assistant-api/internal/ent/channel"
	"assistant-api/internal/ent/channelservicemember"
	"assistant-api/internal/ent/skill"
	"assistant-api/internal/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ChannelServiceMemberCreate is the builder for creating a ChannelServiceMember entity.
type ChannelServiceMemberCreate struct {
	config
	mutation *ChannelServiceMemberMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *ChannelServiceMemberCreate) SetCreatedAt(v time.Time) *ChannelServiceMemberCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ChannelServiceMemberCreate) SetNillableCreatedAt(v *time.Time) *ChannelServiceMemberCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ChannelServiceMemberCreate) SetUpdatedAt(v time.Time) *ChannelServiceMemberCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ChannelServiceMemberCreate) SetNillableUpdatedAt(v *time.Time) *ChannelServiceMemberCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetChannelID sets the "channel_id" field.
func (_c *ChannelServiceMemberCreate) SetChannelID(v uuid.UUID) *ChannelServiceMemberCreate {
	_c.mutation.SetChannelID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ChannelServiceMemberCreate) SetUserID(v uuid.UUID) *ChannelServiceMemberCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetSkillID sets the "skill_id" field.
func (_c *ChannelServiceMemberCreate) SetSkillID(v uuid.UUID) *ChannelServiceMemberCreate {
	_c.mutation.SetSkillID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *ChannelServiceMemberCreate) SetID(v uuid.UUID) *ChannelServiceMemberCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ChannelServiceMemberCreate) SetNillableID(v *uuid.UUID) *ChannelServiceMemberCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_c *ChannelServiceMemberCreate) SetChannel(v *Channel) *ChannelServiceMemberCreate {
	return _c.SetChannelID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *ChannelServiceMemberCreate) SetUser(v *User) *ChannelServiceMemberCreate {
	return _c.SetUserID(v.ID)
}

// SetSkill sets the "skill" edge to the Skill entity.
func (_c *ChannelServiceMemberCreate) SetSkill(v *Skill) *ChannelServiceMemberCreate {
	return _c.SetSkillID(v.ID)
}

// Mutation returns the ChannelServiceMemberMutation object of the builder.
func (_c *ChannelServiceMemberCreate) Mutation() *ChannelServiceMemberMutation {
	return _c.mutation
}

// Save creates the ChannelServiceMember in the database.
func (_c *ChannelServiceMemberCreate) Save(ctx context.Context) (*ChannelServiceMember, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChannelServiceMemberCreate) SaveX(ctx context.Context) *ChannelServiceMember {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChannelServiceMemberCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChannelServiceMemberCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChannelServiceMemberCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := channelservicemember.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := channelservicemember.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := channelservicemember.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChannelServiceMemberCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ChannelServiceMember.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ChannelServiceMember.updated_at"`)}
	}
	if _, ok := _c.mutation.ChannelID(); !ok {
		return &ValidationError{Name: "channel_id", err: errors.New(`ent: missing required field "ChannelServiceMember.channel_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ChannelServiceMember.user_id"`)}
	}
	if _, ok := _c.mutation.SkillID(); !ok {
		return &ValidationError{Name: "skill_id", err: errors.New(`ent: missing required field "ChannelServiceMember.skill_id"`)}
	}
	if len(_c.mutation.ChannelIDs()) == 0 {
		return &ValidationError{Name: "channel", err: errors.New(`ent: missing required edge "ChannelServiceMember.channel"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "ChannelServiceMember.user"`)}
	}
	if len(_c.mutation.SkillIDs()) == 0 {
		return &ValidationError{Name: "skill", err: errors.New(`ent: missing required edge "ChannelServiceMember.skill"`)}
	}
	return nil
}

func (_c *ChannelServiceMemberCreate) sqlSave(ctx context.Context) (*ChannelServiceMember, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChannelServiceMemberCreate) createSpec() (*ChannelServiceMember, *sqlgraph.CreateSpec) {
	var (
		_node = &ChannelServiceMember{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(channelservicemember.Table, sqlgraph.NewFieldSpec(channelservicemember.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(channelservicemember.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(channelservicemember.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   channelservicemember.ChannelTable,
			Columns: []string{channelservicemember.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ChannelID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   channelservicemember.UserTable,
			Columns: []string{channelservicemember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SkillIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   channelservicemember.SkillTable,
			Columns: []string{channelservicemember.SkillColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skill.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SkillID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ChannelServiceMemberCreateBulk is the builder for creating many ChannelServiceMember entities in bulk.
type ChannelServiceMemberCreateBulk struct {
	config
	err      error
	builders []*ChannelServiceMemberCreate
}

// Save creates the ChannelServiceMember entities in the database.
func (_c *ChannelServiceMemberCreateBulk) Save(ctx context.Context) ([]*ChannelServiceMember, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ChannelServiceMember, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChannelServiceMemberMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChannelServiceMemberCreateBulk) SaveX(ctx context.Context) []*ChannelServiceMember {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChannelServiceMemberCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChannelServiceMemberCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
