// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"assistant-api/internal/ent/migrate"

	"assistant-api/internal/ent/action"
	"assistant-api/internal/ent/actionresult"
	"assistant-api/internal/ent/actionroute"
	"assistant-api/internal/ent/channel"
	"assistant-api/internal/ent/channelmessage"
	"assistant-api/internal/ent/channelservicemember"
	"assistant-api/internal/ent/line"
	"assistant-api/internal/ent/skill"
	"assistant-api/internal/ent/slack"
	"assistant-api/internal/ent/slackworkspace"
	"assistant-api/internal/ent/translationlocale"
	"assistant-api/internal/ent/user"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Action is the client for interacting with the Action builders.
	Action *ActionClient
	// ActionResult is the client for interacting with the ActionResult builders.
	ActionResult *ActionResultClient
	// ActionRoute is the client for interacting with the ActionRoute builders.
	ActionRoute *ActionRouteClient
	// Channel is the client for interacting with the Channel builders.
	Channel *ChannelClient
	// ChannelMessage is the client for interacting with the ChannelMessage builders.
	ChannelMessage *ChannelMessageClient
	// ChannelServiceMember is the client for interacting with the ChannelServiceMember builders.
	ChannelServiceMember *ChannelServiceMemberClient
	// Line is the client for interacting with the Line builders.
	Line *LineClient
	// Skill is the client for interacting with the Skill builders.
	Skill *SkillClient
	// Slack is the client for interacting with the Slack builders.
	Slack *SlackClient
	// SlackWorkspace is the client for interacting with the SlackWorkspace builders.
	SlackWorkspace *SlackWorkspaceClient
	// TranslationLocale is the client for interacting with the TranslationLocale builders.
	TranslationLocale *TranslationLocaleClient
	// User is the client for interacting with the User builders.
	User *UserClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Action = NewActionClient(c.config)
	c.ActionResult = NewActionResultClient(c.config)
	c.ActionRoute = NewActionRouteClient(c.config)
	c.Channel = NewChannelClient(c.config)
	c.ChannelMessage = NewChannelMessageClient(c.config)
	c.ChannelServiceMember = NewChannelServiceMemberClient(c.config)
	c.Line = NewLineClient(c.config)
	c.Skill = NewSkillClient(c.config)
	c.Slack = NewSlackClient(c.config)
	c.SlackWorkspace = NewSlackWorkspaceClient(c.config)
	c.TranslationLocale = NewTranslationLocaleClient(c.config)
	c.User = NewUserClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                  ctx,
		config:               cfg,
		Action:               NewActionClient(cfg),
		ActionResult:         NewActionResultClient(cfg),
		ActionRoute:          NewActionRouteClient(cfg),
		Channel:              NewChannelClient(cfg),
		ChannelMessage:       NewChannelMessageClient(cfg),
		ChannelServiceMember: NewChannelServiceMemberClient(cfg),
		Line:                 NewLineClient(cfg),
		Skill:                NewSkillClient(cfg),
		Slack:                NewSlackClient(cfg),
		SlackWorkspace:       NewSlackWorkspaceClient(cfg),
		TranslationLocale:    NewTranslationLocaleClient(cfg),
		User:                 NewUserClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                  ctx,
		config:               cfg,
		Action:               NewActionClient(cfg),
		ActionResult:         NewActionResultClient(cfg),
		ActionRoute:          NewActionRouteClient(cfg),
		Channel:              NewChannelClient(cfg),
		ChannelMessage:       NewChannelMessageClient(cfg),
		ChannelServiceMember: NewChannelServiceMemberClient(cfg),
		Line:                 NewLineClient(cfg),
		Skill:                NewSkillClient(cfg),
		Slack:                NewSlackClient(cfg),
		SlackWorkspace:       NewSlackWorkspaceClient(cfg),
		TranslationLocale:    NewTranslationLocaleClient(cfg),
		User:                 NewUserClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Action.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.Action, c.ActionResult, c.ActionRoute, c.Channel, c.ChannelMessage,
		c.ChannelServiceMember, c.Line, c.Skill, c.Slack, c.SlackWorkspace,
		c.TranslationLocale, c.User,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.Action, c.ActionResult, c.ActionRoute, c.Channel, c.ChannelMessage,
		c.ChannelServiceMember, c.Line, c.Skill, c.Slack, c.SlackWorkspace,
		c.TranslationLocale, c.User,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *ActionMutation:
		return c.Action.mutate(ctx, m)
	case *ActionResultMutation:
		return c.ActionResult.mutate(ctx, m)
	case *ActionRouteMutation:
		return c.ActionRoute.mutate(ctx, m)
	case *ChannelMutation:
		return c.Channel.mutate(ctx, m)
	case *ChannelMessageMutation:
		return c.ChannelMessage.mutate(ctx, m)
	case *ChannelServiceMemberMutation:
		return c.ChannelServiceMember.mutate(ctx, m)
	case *LineMutation:
		return c.Line.mutate(ctx, m)
	case *SkillMutation:
		return c.Skill.mutate(ctx, m)
	case *SlackMutation:
		return c.Slack.mutate(ctx, m)
	case *SlackWorkspaceMutation:
		return c.SlackWorkspace.mutate(ctx, m)
	case *TranslationLocaleMutation:
		return c.TranslationLocale.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// ActionClient is a client for the Action schema.
type ActionClient struct {
	config
}

// NewActionClient returns a client for the Action from the given config.
func NewActionClient(c config) *ActionClient {
	return &ActionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `action.Hooks(f(g(h())))`.
func (c *ActionClient) Use(hooks ...Hook) {
	c.hooks.Action = append(c.hooks.Action, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `action.Intercept(f(g(h())))`.
func (c *ActionClient) Intercept(interceptors ...Interceptor) {
	c.inters.Action = append(c.inters.Action, interceptors...)
}

// Create returns a builder for creating a Action entity.
func (c *ActionClient) Create() *ActionCreate {
	mutation := newActionMutation(c.config, OpCreate)
	return &ActionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Action entities.
func (c *ActionClient) CreateBulk(builders ...*ActionCreate) *ActionCreateBulk {
	return &ActionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ActionClient) MapCreateBulk(slice any, setFunc func(*ActionCreate, int)) *ActionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ActionCreateBulk{err: fmt.Errorf("calling to ActionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ActionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ActionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Action.
func (c *ActionClient) Update() *ActionUpdate {
	mutation := newActionMutation(c.config, OpUpdate)
	return &ActionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ActionClient) UpdateOne(_m *Action) *ActionUpdateOne {
	mutation := newActionMutation(c.config, OpUpdateOne, withAction(_m))
	return &ActionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ActionClient) UpdateOneID(id uuid.UUID) *ActionUpdateOne {
	mutation := newActionMutation(c.config, OpUpdateOne, withActionID(id))
	return &ActionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Action.
func (c *ActionClient) Delete() *ActionDelete {
	mutation := newActionMutation(c.config, OpDelete)
	return &ActionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ActionClient) DeleteOne(_m *Action) *ActionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ActionClient) DeleteOneID(id uuid.UUID) *ActionDeleteOne {
	builder := c.Delete().Where(action.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ActionDeleteOne{builder}
}

// Query returns a query builder for Action.
func (c *ActionClient) Query() *ActionQuery {
	return &ActionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAction},
		inters: c.Interceptors(),
	}
}

// Get returns a Action entity by its id.
func (c *ActionClient) Get(ctx context.Context, id uuid.UUID) (*Action, error) {
	return c.Query().Where(action.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ActionClient) GetX(ctx context.Context, id uuid.UUID) *Action {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QuerySkill queries the skill edge of a Action.
func (c *ActionClient) QuerySkill(_m *Action) *SkillQuery {
	query := (&SkillClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(action.Table, action.FieldID, id),
			sqlgraph.To(skill.Table, skill.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, action.SkillTable, action.SkillColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryRoutes queries the routes edge of a Action.
func (c *ActionClient) QueryRoutes(_m *Action) *ActionRouteQuery {
	query := (&ActionRouteClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(action.Table, action.FieldID, id),
			sqlgraph.To(actionroute.Table, actionroute.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, action.RoutesTable, action.RoutesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ActionClient) Hooks() []Hook {
	return c.hooks.Action
}

// Interceptors returns the client interceptors.
func (c *ActionClient) Interceptors() []Interceptor {
	return c.inters.Action
}

func (c *ActionClient) mutate(ctx context.Context, m *ActionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ActionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ActionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ActionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ActionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Action mutation op: %q", m.Op())
	}
}

// ActionResultClient is a client for the ActionResult schema.
type ActionResultClient struct {
	config
}

// NewActionResultClient returns a client for the ActionResult from the given config.
func NewActionResultClient(c config) *ActionResultClient {
	return &ActionResultClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `actionresult.Hooks(f(g(h())))`.
func (c *ActionResultClient) Use(hooks ...Hook) {
	c.hooks.ActionResult = append(c.hooks.ActionResult, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `actionresult.Intercept(f(g(h())))`.
func (c *ActionResultClient) Intercept(interceptors ...Interceptor) {
	c.inters.ActionResult = append(c.inters.ActionResult, interceptors...)
}

// Create returns a builder for creating a ActionResult entity.
func (c *ActionResultClient) Create() *ActionResultCreate {
	mutation := newActionResultMutation(c.config, OpCreate)
	return &ActionResultCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ActionResult entities.
func (c *ActionResultClient) CreateBulk(builders ...*ActionResultCreate) *ActionResultCreateBulk {
	return &ActionResultCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ActionResultClient) MapCreateBulk(slice any, setFunc func(*ActionResultCreate, int)) *ActionResultCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ActionResultCreateBulk{err: fmt.Errorf("calling to ActionResultClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ActionResultCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ActionResultCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ActionResult.
func (c *ActionResultClient) Update() *ActionResultUpdate {
	mutation := newActionResultMutation(c.config, OpUpdate)
	return &ActionResultUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ActionResultClient) UpdateOne(_m *ActionResult) *ActionResultUpdateOne {
	mutation := newActionResultMutation(c.config, OpUpdateOne, withActionResult(_m))
	return &ActionResultUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ActionResultClient) UpdateOneID(id uuid.UUID) *ActionResultUpdateOne {
	mutation := newActionResultMutation(c.config, OpUpdateOne, withActionResultID(id))
	return &ActionResultUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ActionResult.
func (c *ActionResultClient) Delete() *ActionResultDelete {
	mutation := newActionResultMutation(c.config, OpDelete)
	return &ActionResultDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ActionResultClient) DeleteOne(_m *ActionResult) *ActionResultDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ActionResultClient) DeleteOneID(id uuid.UUID) *ActionResultDeleteOne {
	builder := c.Delete().Where(actionresult.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ActionResultDeleteOne{builder}
}

// Query returns a query builder for ActionResult.
func (c *ActionResultClient) Query() *ActionResultQuery {
	return &ActionResultQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeActionResult},
		inters: c.Interceptors(),
	}
}

// Get returns a ActionResult entity by its id.
func (c *ActionResultClient) Get(ctx context.Context, id uuid.UUID) (*ActionResult, error) {
	return c.Query().Where(actionresult.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ActionResultClient) GetX(ctx context.Context, id uuid.UUID) *ActionResult {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryAction queries the action edge of a ActionResult.
func (c *ActionResultClient) QueryAction(_m *ActionResult) *ActionQuery {
	query := (&ActionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(actionresult.Table, actionresult.FieldID, id),
			sqlgraph.To(action.Table, action.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, actionresult.ActionTable, actionresult.ActionColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryChannelMessage queries the channel_message edge of a ActionResult.
func (c *ActionResultClient) QueryChannelMessage(_m *ActionResult) *ChannelMessageQuery {
	query := (&ChannelMessageClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(actionresult.Table, actionresult.FieldID, id),
			sqlgraph.To(channelmessage.Table, channelmessage.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, actionresult.ChannelMessageTable, actionresult.ChannelMessageColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ActionResultClient) Hooks() []Hook {
	return c.hooks.ActionResult
}

// Interceptors returns the client interceptors.
func (c *ActionResultClient) Interceptors() []Interceptor {
	return c.inters.ActionResult
}

func (c *ActionResultClient) mutate(ctx context.Context, m *ActionResultMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ActionResultCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ActionResultUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ActionResultUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ActionResultDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ActionResult mutation op: %q", m.Op())
	}
}

// ActionRouteClient is a client for the ActionRoute schema.
type ActionRouteClient struct {
	config
}

// NewActionRouteClient returns a client for the ActionRoute from the given config.
func NewActionRouteClient(c config) *ActionRouteClient {
	return &ActionRouteClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `actionroute.Hooks(f(g(h())))`.
func (c *ActionRouteClient) Use(hooks ...Hook) {
	c.hooks.ActionRoute = append(c.hooks.ActionRoute, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `actionroute.Intercept(f(g(h())))`.
func (c *ActionRouteClient) Intercept(interceptors ...Interceptor) {
	c.inters.ActionRoute = append(c.inters.ActionRoute, interceptors...)
}

// Create returns a builder for creating a ActionRoute entity.
func (c *ActionRouteClient) Create() *ActionRouteCreate {
	mutation := newActionRouteMutation(c.config, OpCreate)
	return &ActionRouteCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ActionRoute entities.
func (c *ActionRouteClient) CreateBulk(builders ...*ActionRouteCreate) *ActionRouteCreateBulk {
	return &ActionRouteCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ActionRouteClient) MapCreateBulk(slice any, setFunc func(*ActionRouteCreate, int)) *ActionRouteCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ActionRouteCreateBulk{err: fmt.Errorf("calling to ActionRouteClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ActionRouteCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ActionRouteCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ActionRoute.
func (c *ActionRouteClient) Update() *ActionRouteUpdate {
	mutation := newActionRouteMutation(c.config, OpUpdate)
	return &ActionRouteUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ActionRouteClient) UpdateOne(_m *ActionRoute) *ActionRouteUpdateOne {
	mutation := newActionRouteMutation(c.config, OpUpdateOne, withActionRoute(_m))
	return &ActionRouteUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ActionRouteClient) UpdateOneID(id uuid.UUID) *ActionRouteUpdateOne {
	mutation := newActionRouteMutation(c.config, OpUpdateOne, withActionRouteID(id))
	return &ActionRouteUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ActionRoute.
func (c *ActionRouteClient) Delete() *ActionRouteDelete {
	mutation := newActionRouteMutation(c.config, OpDelete)
	return &ActionRouteDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ActionRouteClient) DeleteOne(_m *ActionRoute) *ActionRouteDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ActionRouteClient) DeleteOneID(id uuid.UUID) *ActionRouteDeleteOne {
	builder := c.Delete().Where(actionroute.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ActionRouteDeleteOne{builder}
}

// Query returns a query builder for ActionRoute.
func (c *ActionRouteClient) Query() *ActionRouteQuery {
	return &ActionRouteQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeActionRoute},
		inters: c.Interceptors(),
	}
}

// Get returns a ActionRoute entity by its id.
func (c *ActionRouteClient) Get(ctx context.Context, id uuid.UUID) (*ActionRoute, error) {
	return c.Query().Where(actionroute.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ActionRouteClient) GetX(ctx context.Context, id uuid.UUID) *ActionRoute {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryAction queries the action edge of a ActionRoute.
func (c *ActionRouteClient) QueryAction(_m *ActionRoute) *ActionQuery {
	query := (&ActionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(actionroute.Table, actionroute.FieldID, id),
			sqlgraph.To(action.Table, action.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, actionroute.ActionTable, actionroute.ActionColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ActionRouteClient) Hooks() []Hook {
	return c.hooks.ActionRoute
}

// Interceptors returns the client interceptors.
func (c *ActionRouteClient) Interceptors() []Interceptor {
	return c.inters.ActionRoute
}

func (c *ActionRouteClient) mutate(ctx context.Context, m *ActionRouteMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ActionRouteCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ActionRouteUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ActionRouteUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ActionRouteDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ActionRoute mutation op: %q", m.Op())
	}
}

// ChannelClient is a client for the Channel schema.
type ChannelClient struct {
	config
}

// NewChannelClient returns a client for the Channel from the given config.
func NewChannelClient(c config) *ChannelClient {
	return &ChannelClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `channel.Hooks(f(g(h())))`.
func (c *ChannelClient) Use(hooks ...Hook) {
	c.hooks.Channel = append(c.hooks.Channel, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `channel.Intercept(f(g(h())))`.
func (c *ChannelClient) Intercept(interceptors ...Interceptor) {
	c.inters.Channel = append(c.inters.Channel, interceptors...)
}

// Create returns a builder for creating a Channel entity.
func (c *ChannelClient) Create() *ChannelCreate {
	mutation := newChannelMutation(c.config, OpCreate)
	return &ChannelCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Channel entities.
func (c *ChannelClient) CreateBulk(builders ...*ChannelCreate) *ChannelCreateBulk {
	return &ChannelCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ChannelClient) MapCreateBulk(slice any, setFunc func(*ChannelCreate, int)) *ChannelCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ChannelCreateBulk{err: fmt.Errorf("calling to ChannelClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ChannelCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ChannelCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Channel.
func (c *ChannelClient) Update() *ChannelUpdate {
	mutation := newChannelMutation(c.config, OpUpdate)
	return &ChannelUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ChannelClient) UpdateOne(_m *Channel) *ChannelUpdateOne {
	mutation := newChannelMutation(c.config, OpUpdateOne, withChannel(_m))
	return &ChannelUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ChannelClient) UpdateOneID(id uuid.UUID) *ChannelUpdateOne {
	mutation := newChannelMutation(c.config, OpUpdateOne, withChannelID(id))
	return &ChannelUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Channel.
func (c *ChannelClient) Delete() *ChannelDelete {
	mutation := newChannelMutation(c.config, OpDelete)
	return &ChannelDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ChannelClient) DeleteOne(_m *Channel) *ChannelDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ChannelClient) DeleteOneID(id uuid.UUID) *ChannelDeleteOne {
	builder := c.Delete().Where(channel.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ChannelDeleteOne{builder}
}

// Query returns a query builder for Channel.
func (c *ChannelClient) Query() *ChannelQuery {
	return &ChannelQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeChannel},
		inters: c.Interceptors(),
	}
}

// Get returns a Channel entity by its id.
func (c *ChannelClient) Get(ctx context.Context, id uuid.UUID) (*Channel, error) {
	return c.Query().Where(channel.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ChannelClient) GetX(ctx context.Context, id uuid.UUID) *Channel {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryMessages queries the messages edge of a Channel.
func (c *ChannelClient) QueryMessages(_m *Channel) *ChannelMessageQuery {
	query := (&ChannelMessageClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(channel.Table, channel.FieldID, id),
			sqlgraph.To(channelmessage.Table, channelmessage.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, channel.MessagesTable, channel.MessagesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryServiceMembers queries the service_members edge of a Channel.
func (c *ChannelClient) QueryServiceMembers(_m *Channel) *ChannelServiceMemberQuery {
	query := (&ChannelServiceMemberClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(channel.Table, channel.FieldID, id),
			sqlgraph.To(channelservicemember.Table, channelservicemember.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, channel.ServiceMembersTable, channel.ServiceMembersColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryTranslationLocales queries the translation_locales edge of a Channel.
func (c *ChannelClient) QueryTranslationLocales(_m *Channel) *TranslationLocaleQuery {
	query := (&TranslationLocaleClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(channel.Table, channel.FieldID, id),
			sqlgraph.To(translationlocale.Table, translationlocale.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, channel.TranslationLocalesTable, channel.TranslationLocalesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ChannelClient) Hooks() []Hook {
	return c.hooks.Channel
}

// Interceptors returns the client interceptors.
func (c *ChannelClient) Interceptors() []Interceptor {
	return c.inters.Channel
}

func (c *ChannelClient) mutate(ctx context.Context, m *ChannelMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ChannelCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ChannelUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ChannelUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ChannelDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Channel mutation op: %q", m.Op())
	}
}

// ChannelMessageClient is a client for the ChannelMessage schema.
// 中文說明：此 client 會操作含 triggered_message_id 的訊息模型，讓系統輸出可以追溯觸發來源。
type ChannelMessageClient struct {
	config
}

// NewChannelMessageClient returns a client for the ChannelMessage from the given config.
func NewChannelMessageClient(c config) *ChannelMessageClient {
	return &ChannelMessageClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `channelmessage.Hooks(f(g(h())))`.
func (c *ChannelMessageClient) Use(hooks ...Hook) {
	c.hooks.ChannelMessage = append(c.hooks.ChannelMessage, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `channelmessage.Intercept(f(g(h())))`.
func (c *ChannelMessageClient) Intercept(interceptors ...Interceptor) {
	c.inters.ChannelMessage = append(c.inters.ChannelMessage, interceptors...)
}

// Create returns a builder for creating a ChannelMessage entity.
func (c *ChannelMessageClient) Create() *ChannelMessageCreate {
	mutation := newChannelMessageMutation(c.config, OpCreate)
	return &ChannelMessageCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ChannelMessage entities.
func (c *ChannelMessageClient) CreateBulk(builders ...*ChannelMessageCreate) *ChannelMessageCreateBulk {
	return &ChannelMessageCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ChannelMessageClient) MapCreateBulk(slice any, setFunc func(*ChannelMessageCreate, int)) *ChannelMessageCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ChannelMessageCreateBulk{err: fmt.Errorf("calling to ChannelMessageClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ChannelMessageCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ChannelMessageCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ChannelMessage.
func (c *ChannelMessageClient) Update() *ChannelMessageUpdate {
	mutation := newChannelMessageMutation(c.config, OpUpdate)
	return &ChannelMessageUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ChannelMessageClient) UpdateOne(_m *ChannelMessage) *ChannelMessageUpdateOne {
	mutation := newChannelMessageMutation(c.config, OpUpdateOne, withChannelMessage(_m))
	return &ChannelMessageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ChannelMessageClient) UpdateOneID(id uuid.UUID) *ChannelMessageUpdateOne {
	mutation := newChannelMessageMutation(c.config, OpUpdateOne, withChannelMessageID(id))
	return &ChannelMessageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ChannelMessage.
func (c *ChannelMessageClient) Delete() *ChannelMessageDelete {
	mutation := newChannelMessageMutation(c.config, OpDelete)
	return &ChannelMessageDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ChannelMessageClient) DeleteOne(_m *ChannelMessage) *ChannelMessageDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ChannelMessageClient) DeleteOneID(id uuid.UUID) *ChannelMessageDeleteOne {
	builder := c.Delete().Where(channelmessage.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ChannelMessageDeleteOne{builder}
}

// Query returns a query builder for ChannelMessage.
func (c *ChannelMessageClient) Query() *ChannelMessageQuery {
	return &ChannelMessageQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeChannelMessage},
		inters: c.Interceptors(),
	}
}

// Get returns a ChannelMessage entity by its id.
func (c *ChannelMessageClient) Get(ctx context.Context, id uuid.UUID) (*ChannelMessage, error) {
	return c.Query().Where(channelmessage.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ChannelMessageClient) GetX(ctx context.Context, id uuid.UUID) *ChannelMessage {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryChannel queries the channel edge of a ChannelMessage.
func (c *ChannelMessageClient) QueryChannel(_m *ChannelMessage) *ChannelQuery {
	query := (&ChannelClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(channelmessage.Table, channelmessage.FieldID, id),
			sqlgraph.To(channel.Table, channel.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, channelmessage.ChannelTable, channelmessage.ChannelColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryTriggeredMessage queries the triggered_message edge of a ChannelMessage.
func (c *ChannelMessageClient) QueryTriggeredMessage(_m *ChannelMessage) *ChannelMessageQuery {
	query := (&ChannelMessageClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(channelmessage.Table, channelmessage.FieldID, id),
			sqlgraph.To(channelmessage.Table, channelmessage.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, channelmessage.TriggeredMessageTable, channelmessage.TriggeredMessageColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryTriggeredMessages queries the triggered_messages edge of a ChannelMessage.
func (c *ChannelMessageClient) QueryTriggeredMessages(_m *ChannelMessage) *ChannelMessageQuery {
	query := (&ChannelMessageClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(channelmessage.Table, channelmessage.FieldID, id),
			sqlgraph.To(channelmessage.Table, channelmessage.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, channelmessage.TriggeredMessagesTable, channelmessage.TriggeredMessagesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ChannelMessageClient) Hooks() []Hook {
	return c.hooks.ChannelMessage
}

// Interceptors returns the client interceptors.
func (c *ChannelMessageClient) Interceptors() []Interceptor {
	return c.inters.ChannelMessage
}

func (c *ChannelMessageClient) mutate(ctx context.Context, m *ChannelMessageMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ChannelMessageCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ChannelMessageUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ChannelMessageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ChannelMessageDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ChannelMessage mutation op: %q", m.Op())
	}
}

// ChannelServiceMemberClient is a client for the ChannelServiceMember schema.
type ChannelServiceMemberClient struct {
	config
}

// NewChannelServiceMemberClient returns a client for the ChannelServiceMember from the given config.
func NewChannelServiceMemberClient(c config) *ChannelServiceMemberClient {
	return &ChannelServiceMemberClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `channelservicemember.Hooks(f(g(h())))`.
func (c *ChannelServiceMemberClient) Use(hooks ...Hook) {
	c.hooks.ChannelServiceMember = append(c.hooks.ChannelServiceMember, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `channelservicemember.Intercept(f(g(h())))`.
func (c *ChannelServiceMemberClient) Intercept(interceptors ...Interceptor) {
	c.inters.ChannelServiceMember = append(c.inters.ChannelServiceMember, interceptors...)
}

// Create returns a builder for creating a ChannelServiceMember entity.
func (c *ChannelServiceMemberClient) Create() *ChannelServiceMemberCreate {
	mutation := newChannelServiceMemberMutation(c.config, OpCreate)
	return &ChannelServiceMemberCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ChannelServiceMember entities.
func (c *ChannelServiceMemberClient) CreateBulk(builders ...*ChannelServiceMemberCreate) *ChannelServiceMemberCreateBulk {
	return &ChannelServiceMemberCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ChannelServiceMemberClient) MapCreateBulk(slice any, setFunc func(*ChannelServiceMemberCreate, int)) *ChannelServiceMemberCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ChannelServiceMemberCreateBulk{err: fmt.Errorf("calling to ChannelServiceMemberClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ChannelServiceMemberCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ChannelServiceMemberCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ChannelServiceMember.
func (c *ChannelServiceMemberClient) Update() *ChannelServiceMemberUpdate {
	mutation := newChannelServiceMemberMutation(c.config, OpUpdate)
	return &ChannelServiceMemberUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ChannelServiceMemberClient) UpdateOne(_m *ChannelServiceMember) *ChannelServiceMemberUpdateOne {
	mutation := newChannelServiceMemberMutation(c.config, OpUpdateOne, withChannelServiceMember(_m))
	return &ChannelServiceMemberUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ChannelServiceMemberClient) UpdateOneID(id uuid.UUID) *ChannelServiceMemberUpdateOne {
	mutation := newChannelServiceMemberMutation(c.config, OpUpdateOne, withChannelServiceMemberID(id))
	return &ChannelServiceMemberUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ChannelServiceMember.
func (c *ChannelServiceMemberClient) Delete() *ChannelServiceMemberDelete {
	mutation := newChannelServiceMemberMutation(c.config, OpDelete)
	return &ChannelServiceMemberDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ChannelServiceMemberClient) DeleteOne(_m *ChannelServiceMember) *ChannelServiceMemberDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ChannelServiceMemberClient) DeleteOneID(id uuid.UUID) *ChannelServiceMemberDeleteOne {
	builder := c.Delete().Where(channelservicemember.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ChannelServiceMemberDeleteOne{builder}
}

// Query returns a query builder for ChannelServiceMember.
func (c *ChannelServiceMemberClient) Query() *ChannelServiceMemberQuery {
	return &ChannelServiceMemberQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeChannelServiceMember},
		inters: c.Interceptors(),
	}
}

// Get returns a ChannelServiceMember entity by its id.
func (c *ChannelServiceMemberClient) Get(ctx context.Context, id uuid.UUID) (*ChannelServiceMember, error) {
	return c.Query().Where(channelservicemember.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ChannelServiceMemberClient) GetX(ctx context.Context, id uuid.UUID) *ChannelServiceMember {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryChannel queries the channel edge of a ChannelServiceMember.
func (c *ChannelServiceMemberClient) QueryChannel(_m *ChannelServiceMember) *ChannelQuery {
	query := (&ChannelClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(channelservicemember.Table, channelservicemember.FieldID, id),
			sqlgraph.To(channel.Table, channel.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, channelservicemember.ChannelTable, channelservicemember.ChannelColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryUser queries the user edge of a ChannelServiceMember.
func (c *ChannelServiceMemberClient) QueryUser(_m *ChannelServiceMember) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(channelservicemember.Table, channelservicemember.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, channelservicemember.UserTable, channelservicemember.UserColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QuerySkill queries the skill edge of a ChannelServiceMember.
func (c *ChannelServiceMemberClient) QuerySkill(_m *ChannelServiceMember) *SkillQuery {
	query := (&SkillClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(channelservicemember.Table, channelservicemember.FieldID, id),
			sqlgraph.To(skill.Table, skill.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, channelservicemember.SkillTable, channelservicemember.SkillColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ChannelServiceMemberClient) Hooks() []Hook {
	return c.hooks.ChannelServiceMember
}

// Interceptors returns the client interceptors.
func (c *ChannelServiceMemberClient) Interceptors() []Interceptor {
	return c.inters.ChannelServiceMember
}

func (c *ChannelServiceMemberClient) mutate(ctx context.Context, m *ChannelServiceMemberMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ChannelServiceMemberCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ChannelServiceMemberUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ChannelServiceMemberUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ChannelServiceMemberDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ChannelServiceMember mutation op: %q", m.Op())
	}
}

// LineClient is a client for the Line schema.
type LineClient struct {
	config
}

// NewLineClient returns a client for the Line from the given config.
func NewLineClient(c config) *LineClient {
	return &LineClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `line.Hooks(f(g(h())))`.
func (c *LineClient) Use(hooks ...Hook) {
	c.hooks.Line = append(c.hooks.Line, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `line.Intercept(f(g(h())))`.
func (c *LineClient) Intercept(interceptors ...Interceptor) {
	c.inters.Line = append(c.inters.Line, interceptors...)
}

// Create returns a builder for creating a Line entity.
func (c *LineClient) Create() *LineCreate {
	mutation := newLineMutation(c.config, OpCreate)
	return &LineCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Line entities.
func (c *LineClient) CreateBulk(builders ...*LineCreate) *LineCreateBulk {
	return &LineCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *LineClient) MapCreateBulk(slice any, setFunc func(*LineCreate, int)) *LineCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &LineCreateBulk{err: fmt.Errorf("calling to LineClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*LineCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &LineCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Line.
func (c *LineClient) Update() *LineUpdate {
	mutation := newLineMutation(c.config, OpUpdate)
	return &LineUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *LineClient) UpdateOne(_m *Line) *LineUpdateOne {
	mutation := newLineMutation(c.config, OpUpdateOne, withLine(_m))
	return &LineUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *LineClient) UpdateOneID(id uuid.UUID) *LineUpdateOne {
	mutation := newLineMutation(c.config, OpUpdateOne, withLineID(id))
	return &LineUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Line.
func (c *LineClient) Delete() *LineDelete {
	mutation := newLineMutation(c.config, OpDelete)
	return &LineDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *LineClient) DeleteOne(_m *Line) *LineDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *LineClient) DeleteOneID(id uuid.UUID) *LineDeleteOne {
	builder := c.Delete().Where(line.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &LineDeleteOne{builder}
}

// Query returns a query builder for Line.
func (c *LineClient) Query() *LineQuery {
	return &LineQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeLine},
		inters: c.Interceptors(),
	}
}

// Get returns a Line entity by its id.
func (c *LineClient) Get(ctx context.Context, id uuid.UUID) (*Line, error) {
	return c.Query().Where(line.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *LineClient) GetX(ctx context.Context, id uuid.UUID) *Line {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a Line.
func (c *LineClient) QueryUser(_m *Line) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(line.Table, line.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, line.UserTable, line.UserColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *LineClient) Hooks() []Hook {
	return c.hooks.Line
}

// Interceptors returns the client interceptors.
func (c *LineClient) Interceptors() []Interceptor {
	return c.inters.Line
}

func (c *LineClient) mutate(ctx context.Context, m *LineMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&LineCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&LineUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&LineUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&LineDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Line mutation op: %q", m.Op())
	}
}

// SkillClient is a client for the Skill schema.
type SkillClient struct {
	config
}

// NewSkillClient returns a client for the Skill from the given config.
func NewSkillClient(c config) *SkillClient {
	return &SkillClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `skill.Hooks(f(g(h())))`.
func (c *SkillClient) Use(hooks ...Hook) {
	c.hooks.Skill = append(c.hooks.Skill, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `skill.Intercept(f(g(h())))`.
func (c *SkillClient) Intercept(interceptors ...Interceptor) {
	c.inters.Skill = append(c.inters.Skill, interceptors...)
}

// Create returns a builder for creating a Skill entity.
func (c *SkillClient) Create() *SkillCreate {
	mutation := newSkillMutation(c.config, OpCreate)
	return &SkillCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Skill entities.
func (c *SkillClient) CreateBulk(builders ...*SkillCreate) *SkillCreateBulk {
	return &SkillCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SkillClient) MapCreateBulk(slice any, setFunc func(*SkillCreate, int)) *SkillCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SkillCreateBulk{err: fmt.Errorf("calling to SkillClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SkillCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SkillCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Skill.
func (c *SkillClient) Update() *SkillUpdate {
	mutation := newSkillMutation(c.config, OpUpdate)
	return &SkillUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SkillClient) UpdateOne(_m *Skill) *SkillUpdateOne {
	mutation := newSkillMutation(c.config, OpUpdateOne, withSkill(_m))
	return &SkillUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SkillClient) UpdateOneID(id uuid.UUID) *SkillUpdateOne {
	mutation := newSkillMutation(c.config, OpUpdateOne, withSkillID(id))
	return &SkillUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Skill.
func (c *SkillClient) Delete() *SkillDelete {
	mutation := newSkillMutation(c.config, OpDelete)
	return &SkillDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SkillClient) DeleteOne(_m *Skill) *SkillDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SkillClient) DeleteOneID(id uuid.UUID) *SkillDeleteOne {
	builder := c.Delete().Where(skill.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SkillDeleteOne{builder}
}

// Query returns a query builder for Skill.
func (c *SkillClient) Query() *SkillQuery {
	return &SkillQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSkill},
		inters: c.Interceptors(),
	}
}

// Get returns a Skill entity by its id.
func (c *SkillClient) Get(ctx context.Context, id uuid.UUID) (*Skill, error) {
	return c.Query().Where(skill.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SkillClient) GetX(ctx context.Context, id uuid.UUID) *Skill {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryActions queries the actions edge of a Skill.
func (c *SkillClient) QueryActions(_m *Skill) *ActionQuery {
	query := (&ActionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(skill.Table, skill.FieldID, id),
			sqlgraph.To(action.Table, action.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, skill.ActionsTable, skill.ActionsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryChannelServiceMembers queries the channel_service_members edge of a Skill.
func (c *SkillClient) QueryChannelServiceMembers(_m *Skill) *ChannelServiceMemberQuery {
	query := (&ChannelServiceMemberClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(skill.Table, skill.FieldID, id),
			sqlgraph.To(channelservicemember.Table, channelservicemember.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, skill.ChannelServiceMembersTable, skill.ChannelServiceMembersColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryTranslationLocales queries the translation_locales edge of a Skill.
func (c *SkillClient) QueryTranslationLocales(_m *Skill) *TranslationLocaleQuery {
	query := (&TranslationLocaleClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(skill.Table, skill.FieldID, id),
			sqlgraph.To(translationlocale.Table, translationlocale.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, skill.TranslationLocalesTable, skill.TranslationLocalesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *SkillClient) Hooks() []Hook {
	return c.hooks.Skill
}

// Interceptors returns the client interceptors.
func (c *SkillClient) Interceptors() []Interceptor {
	return c.inters.Skill
}

func (c *SkillClient) mutate(ctx context.Context, m *SkillMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SkillCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SkillUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SkillUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SkillDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Skill mutation op: %q", m.Op())
	}
}

// SlackClient is a client for the Slack schema.
type SlackClient struct {
	config
}

// NewSlackClient returns a client for the Slack from the given config.
func NewSlackClient(c config) *SlackClient {
	return &SlackClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `slack.Hooks(f(g(h())))`.
func (c *SlackClient) Use(hooks ...Hook) {
	c.hooks.Slack = append(c.hooks.Slack, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `slack.Intercept(f(g(h())))`.
func (c *SlackClient) Intercept(interceptors ...Interceptor) {
	c.inters.Slack = append(c.inters.Slack, interceptors...)
}

// Create returns a builder for creating a Slack entity.
func (c *SlackClient) Create() *SlackCreate {
	mutation := newSlackMutation(c.config, OpCreate)
	return &SlackCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Slack entities.
func (c *SlackClient) CreateBulk(builders ...*SlackCreate) *SlackCreateBulk {
	return &SlackCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SlackClient) MapCreateBulk(slice any, setFunc func(*SlackCreate, int)) *SlackCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SlackCreateBulk{err: fmt.Errorf("calling to SlackClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SlackCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SlackCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Slack.
func (c *SlackClient) Update() *SlackUpdate {
	mutation := newSlackMutation(c.config, OpUpdate)
	return &SlackUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SlackClient) UpdateOne(_m *Slack) *SlackUpdateOne {
	mutation := newSlackMutation(c.config, OpUpdateOne, withSlack(_m))
	return &SlackUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SlackClient) UpdateOneID(id uuid.UUID) *SlackUpdateOne {
	mutation := newSlackMutation(c.config, OpUpdateOne, withSlackID(id))
	return &SlackUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Slack.
func (c *SlackClient) Delete() *SlackDelete {
	mutation := newSlackMutation(c.config, OpDelete)
	return &SlackDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SlackClient) DeleteOne(_m *Slack) *SlackDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SlackClient) DeleteOneID(id uuid.UUID) *SlackDeleteOne {
	builder := c.Delete().Where(slack.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SlackDeleteOne{builder}
}

// Query returns a query builder for Slack.
func (c *SlackClient) Query() *SlackQuery {
	return &SlackQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSlack},
		inters: c.Interceptors(),
	}
}

// Get returns a Slack entity by its id.
func (c *SlackClient) Get(ctx context.Context, id uuid.UUID) (*Slack, error) {
	return c.Query().Where(slack.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SlackClient) GetX(ctx context.Context, id uuid.UUID) *Slack {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a Slack.
func (c *SlackClient) QueryUser(_m *Slack) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(slack.Table, slack.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, slack.UserTable, slack.UserColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *SlackClient) Hooks() []Hook {
	return c.hooks.Slack
}

// Interceptors returns the client interceptors.
func (c *SlackClient) Interceptors() []Interceptor {
	return c.inters.Slack
}

func (c *SlackClient) mutate(ctx context.Context, m *SlackMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SlackCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SlackUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SlackUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SlackDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Slack mutation op: %q", m.Op())
	}
}

// SlackWorkspaceClient is a client for the SlackWorkspace schema.
type SlackWorkspaceClient struct {
	config
}

// NewSlackWorkspaceClient returns a client for the SlackWorkspace from the given config.
func NewSlackWorkspaceClient(c config) *SlackWorkspaceClient {
	return &SlackWorkspaceClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `slackworkspace.Hooks(f(g(h())))`.
func (c *SlackWorkspaceClient) Use(hooks ...Hook) {
	c.hooks.SlackWorkspace = append(c.hooks.SlackWorkspace, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `slackworkspace.Intercept(f(g(h())))`.
func (c *SlackWorkspaceClient) Intercept(interceptors ...Interceptor) {
	c.inters.SlackWorkspace = append(c.inters.SlackWorkspace, interceptors...)
}

// Create returns a builder for creating a SlackWorkspace entity.
func (c *SlackWorkspaceClient) Create() *SlackWorkspaceCreate {
	mutation := newSlackWorkspaceMutation(c.config, OpCreate)
	return &SlackWorkspaceCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SlackWorkspace entities.
func (c *SlackWorkspaceClient) CreateBulk(builders ...*SlackWorkspaceCreate) *SlackWorkspaceCreateBulk {
	return &SlackWorkspaceCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SlackWorkspaceClient) MapCreateBulk(slice any, setFunc func(*SlackWorkspaceCreate, int)) *SlackWorkspaceCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SlackWorkspaceCreateBulk{err: fmt.Errorf("calling to SlackWorkspaceClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SlackWorkspaceCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SlackWorkspaceCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SlackWorkspace.
func (c *SlackWorkspaceClient) Update() *SlackWorkspaceUpdate {
	mutation := newSlackWorkspaceMutation(c.config, OpUpdate)
	return &SlackWorkspaceUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SlackWorkspaceClient) UpdateOne(_m *SlackWorkspace) *SlackWorkspaceUpdateOne {
	mutation := newSlackWorkspaceMutation(c.config, OpUpdateOne, withSlackWorkspace(_m))
	return &SlackWorkspaceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SlackWorkspaceClient) UpdateOneID(id uuid.UUID) *SlackWorkspaceUpdateOne {
	mutation := newSlackWorkspaceMutation(c.config, OpUpdateOne, withSlackWorkspaceID(id))
	return &SlackWorkspaceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SlackWorkspace.
func (c *SlackWorkspaceClient) Delete() *SlackWorkspaceDelete {
	mutation := newSlackWorkspaceMutation(c.config, OpDelete)
	return &SlackWorkspaceDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SlackWorkspaceClient) DeleteOne(_m *SlackWorkspace) *SlackWorkspaceDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SlackWorkspaceClient) DeleteOneID(id uuid.UUID) *SlackWorkspaceDeleteOne {
	builder := c.Delete().Where(slackworkspace.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SlackWorkspaceDeleteOne{builder}
}

// Query returns a query builder for SlackWorkspace.
func (c *SlackWorkspaceClient) Query() *SlackWorkspaceQuery {
	return &SlackWorkspaceQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSlackWorkspace},
		inters: c.Interceptors(),
	}
}

// Get returns a SlackWorkspace entity by its id.
func (c *SlackWorkspaceClient) Get(ctx context.Context, id uuid.UUID) (*SlackWorkspace, error) {
	return c.Query().Where(slackworkspace.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SlackWorkspaceClient) GetX(ctx context.Context, id uuid.UUID) *SlackWorkspace {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SlackWorkspaceClient) Hooks() []Hook {
	return c.hooks.SlackWorkspace
}

// Interceptors returns the client interceptors.
func (c *SlackWorkspaceClient) Interceptors() []Interceptor {
	return c.inters.SlackWorkspace
}

func (c *SlackWorkspaceClient) mutate(ctx context.Context, m *SlackWorkspaceMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SlackWorkspaceCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SlackWorkspaceUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SlackWorkspaceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SlackWorkspaceDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown SlackWorkspace mutation op: %q", m.Op())
	}
}

// TranslationLocaleClient is a client for the TranslationLocale schema.
type TranslationLocaleClient struct {
	config
}

// NewTranslationLocaleClient returns a client for the TranslationLocale from the given config.
func NewTranslationLocaleClient(c config) *TranslationLocaleClient {
	return &TranslationLocaleClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `translationlocale.Hooks(f(g(h())))`.
func (c *TranslationLocaleClient) Use(hooks ...Hook) {
	c.hooks.TranslationLocale = append(c.hooks.TranslationLocale, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `translationlocale.Intercept(f(g(h())))`.
func (c *TranslationLocaleClient) Intercept(interceptors ...Interceptor) {
	c.inters.TranslationLocale = append(c.inters.TranslationLocale, interceptors...)
}

// Create returns a builder for creating a TranslationLocale entity.
func (c *TranslationLocaleClient) Create() *TranslationLocaleCreate {
	mutation := newTranslationLocaleMutation(c.config, OpCreate)
	return &TranslationLocaleCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of TranslationLocale entities.
func (c *TranslationLocaleClient) CreateBulk(builders ...*TranslationLocaleCreate) *TranslationLocaleCreateBulk {
	return &TranslationLocaleCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TranslationLocaleClient) MapCreateBulk(slice any, setFunc func(*TranslationLocaleCreate, int)) *TranslationLocaleCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TranslationLocaleCreateBulk{err: fmt.Errorf("calling to TranslationLocaleClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TranslationLocaleCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TranslationLocaleCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for TranslationLocale.
func (c *TranslationLocaleClient) Update() *TranslationLocaleUpdate {
	mutation := newTranslationLocaleMutation(c.config, OpUpdate)
	return &TranslationLocaleUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TranslationLocaleClient) UpdateOne(_m *TranslationLocale) *TranslationLocaleUpdateOne {
	mutation := newTranslationLocaleMutation(c.config, OpUpdateOne, withTranslationLocale(_m))
	return &TranslationLocaleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TranslationLocaleClient) UpdateOneID(id uuid.UUID) *TranslationLocaleUpdateOne {
	mutation := newTranslationLocaleMutation(c.config, OpUpdateOne, withTranslationLocaleID(id))
	return &TranslationLocaleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for TranslationLocale.
func (c *TranslationLocaleClient) Delete() *TranslationLocaleDelete {
	mutation := newTranslationLocaleMutation(c.config, OpDelete)
	return &TranslationLocaleDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TranslationLocaleClient) DeleteOne(_m *TranslationLocale) *TranslationLocaleDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TranslationLocaleClient) DeleteOneID(id uuid.UUID) *TranslationLocaleDeleteOne {
	builder := c.Delete().Where(translationlocale.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TranslationLocaleDeleteOne{builder}
}

// Query returns a query builder for TranslationLocale.
func (c *TranslationLocaleClient) Query() *TranslationLocaleQuery {
	return &TranslationLocaleQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTranslationLocale},
		inters: c.Interceptors(),
	}
}

// Get returns a TranslationLocale entity by its id.
func (c *TranslationLocaleClient) Get(ctx context.Context, id uuid.UUID) (*TranslationLocale, error) {
	return c.Query().Where(translationlocale.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TranslationLocaleClient) GetX(ctx context.Context, id uuid.UUID) *TranslationLocale {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryChannel queries the channel edge of a TranslationLocale.
func (c *TranslationLocaleClient) QueryChannel(_m *TranslationLocale) *ChannelQuery {
	query := (&ChannelClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(translationlocale.Table, translationlocale.FieldID, id),
			sqlgraph.To(channel.Table, channel.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, translationlocale.ChannelTable, translationlocale.ChannelColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QuerySkill queries the skill edge of a TranslationLocale.
func (c *TranslationLocaleClient) QuerySkill(_m *TranslationLocale) *SkillQuery {
	query := (&SkillClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(translationlocale.Table, translationlocale.FieldID, id),
			sqlgraph.To(skill.Table, skill.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, translationlocale.SkillTable, translationlocale.SkillColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryOwner queries the owner edge of a TranslationLocale.
func (c *TranslationLocaleClient) QueryOwner(_m *TranslationLocale) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(translationlocale.Table, translationlocale.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, translationlocale.OwnerTable, translationlocale.OwnerColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TranslationLocaleClient) Hooks() []Hook {
	return c.hooks.TranslationLocale
}

// Interceptors returns the client interceptors.
func (c *TranslationLocaleClient) Interceptors() []Interceptor {
	return c.inters.TranslationLocale
}

func (c *TranslationLocaleClient) mutate(ctx context.Context, m *TranslationLocaleMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TranslationLocaleCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TranslationLocaleUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TranslationLocaleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TranslationLocaleDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown TranslationLocale mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCreateBulk{err: fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(_m *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(_m))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id uuid.UUID) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(_m *User) *UserDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id uuid.UUID) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id uuid.UUID) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id uuid.UUID) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryLine queries the line edge of a User.
func (c *UserClient) QueryLine(_m *User) *LineQuery {
	query := (&LineClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(line.Table, line.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, user.LineTable, user.LineColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QuerySlack queries the slack edge of a User.
func (c *UserClient) QuerySlack(_m *User) *SlackQuery {
	query := (&SlackClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(slack.Table, slack.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, user.SlackTable, user.SlackColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryChannelServiceMembers queries the channel_service_members edge of a User.
func (c *UserClient) QueryChannelServiceMembers(_m *User) *ChannelServiceMemberQuery {
	query := (&ChannelServiceMemberClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(channelservicemember.Table, channelservicemember.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, user.ChannelServiceMembersTable, user.ChannelServiceMembersColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryOwnedTranslationLocales queries the owned_translation_locales edge of a User.
func (c *UserClient) QueryOwnedTranslationLocales(_m *User) *TranslationLocaleQuery {
	query := (&TranslationLocaleClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(translationlocale.Table, translationlocale.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, user.OwnedTranslationLocalesTable, user.OwnedTranslationLocalesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	return c.inters.User
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Action, ActionResult, ActionRoute, Channel, ChannelMessage,
		ChannelServiceMember, Line, Skill, Slack, SlackWorkspace, TranslationLocale,
		User []ent.Hook
	}
	inters struct {
		Action, ActionResult, ActionRoute, Channel, ChannelMessage,
		ChannelServiceMember, Line, Skill, Slack, SlackWorkspace, TranslationLocale,
		User []ent.Interceptor
	}
)
