// Code generated by ent, DO NOT EDIT.

package ent

import (
	"assistant-api/internal/ent/slack"
	"assistant-api/internal/ent/user"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Slack 綁定資訊
type Slack struct {
	config `json:"-"`
	// ID of the ent.
	// 全域唯一主鍵 UUID
	ID uuid.UUID `json:"id,omitempty"`
	// Slack workspace/team ID
	TeamID string `json:"team_id,omitempty"`
	// Slack 平台使用者 ID
	SlackUserID string `json:"slack_user_id,omitempty"`
	// Slack 顯示名稱
	DisplayName *string `json:"display_name,omitempty"`
	// Slack 帳號 email
	Email *string `json:"email,omitempty"`
	// Slack 大頭貼 URL
	Picture *string `json:"picture,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SlackQuery when eager-loading is set.
	Edges        SlackEdges `json:"edges"`
	slack_user   *uuid.UUID
	selectValues sql.SelectValues
}

// SlackEdges holds the relations/edges for other nodes in the graph.
type SlackEdges struct {
	// Slack 帳號對應的系統使用者
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
	// totalCount holds the count of the edges above.
	totalCount [1]map[string]int
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SlackEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Slack) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case slack.FieldTeamID, slack.FieldSlackUserID, slack.FieldDisplayName, slack.FieldEmail, slack.FieldPicture:
			values[i] = new(sql.NullString)
		case slack.FieldID:
			values[i] = new(uuid.UUID)
		case slack.ForeignKeys[0]: // slack_user
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Slack fields.
func (_m *Slack) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case slack.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case slack.FieldTeamID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field team_id", values[i])
			} else if value.Valid {
				_m.TeamID = value.String
			}
		case slack.FieldSlackUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field slack_user_id", values[i])
			} else if value.Valid {
				_m.SlackUserID = value.String
			}
		case slack.FieldDisplayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display_name", values[i])
			} else if value.Valid {
				_m.DisplayName = new(string)
				*_m.DisplayName = value.String
			}
		case slack.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = new(string)
				*_m.Email = value.String
			}
		case slack.FieldPicture:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field picture", values[i])
			} else if value.Valid {
				_m.Picture = new(string)
				*_m.Picture = value.String
			}
		case slack.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field slack_user", values[i])
			} else if value.Valid {
				_m.slack_user = new(uuid.UUID)
				*_m.slack_user = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Slack.
// This includes values selected through modifiers, order, etc.
func (_m *Slack) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the Slack entity.
func (_m *Slack) QueryUser() *UserQuery {
	return NewSlackClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this Slack.
// Note that you need to call Slack.Unwrap() before calling this method if this Slack
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Slack) Update() *SlackUpdateOne {
	return NewSlackClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Slack entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Slack) Unwrap() *Slack {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Slack is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Slack) String() string {
	var builder strings.Builder
	builder.WriteString("Slack(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("team_id=")
	builder.WriteString(_m.TeamID)
	builder.WriteString(", ")
	builder.WriteString("slack_user_id=")
	builder.WriteString(_m.SlackUserID)
	builder.WriteString(", ")
	if v := _m.DisplayName; v != nil {
		builder.WriteString("display_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Email; v != nil {
		builder.WriteString("email=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Picture; v != nil {
		builder.WriteString("picture=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// Slacks is a parsable slice of Slack.
type Slacks []*Slack
