// Code generated by ent, DO NOT EDIT.

package ent

import (
	"assistant-api/internal/ent/channel"
	"assistant-api/internal/ent/todo"
	"assistant-api/internal/ent/todocandidate"
	"assistant-api/internal/ent/user"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Todo Reminder 正式待辦事項
type Todo struct {
	config `json:"-"`
	// ID of the ent.
	// 全域唯一主鍵 UUID
	ID uuid.UUID `json:"id,omitempty"`
	// 建立時間
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 最後更新時間
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 正式待辦所屬 channel ID；產品查詢與權限邊界使用
	ChannelID uuid.UUID `json:"channel_id,omitempty"`
	// 此待辦所屬使用者 ID；每個人都有自己的 Todo row，可獨立修改標題與時間
	OwnerUserID uuid.UUID `json:"owner_user_id,omitempty"`
	// 來源 Todo candidate ID；只用來回溯 AI 分析與 promotion evidence，人工建立的純 Todo 可為空
	SourceCandidateID *uuid.UUID `json:"source_candidate_id,omitempty"`
	// 正式待辦狀態；active 代表仍需追蹤或提醒
	Status todo.Status `json:"status,omitempty"`
	// 事：正式待辦要完成的事項標題，供列表與提醒直接顯示
	Title string `json:"title,omitempty"`
	// 時：正式提醒或到期時間；沒有時間的待辦可先為空
	DueAt *time.Time `json:"due_at,omitempty"`
	// 時：due_at 使用的 IANA timezone，例如 Asia/Taipei
	DueTimezone string `json:"due_timezone,omitempty"`
	// 時：時間精度，描述 due_at 是精確時間、日期或相對區間
	DuePrecision todo.DuePrecision `json:"due_precision,omitempty"`
	// 地：待辦發生或交付的地點字面；目前 promotion 沒有抽到時保持空值
	LocationText string `json:"location_text,omitempty"`
	// 物：待辦涉及的文件、物品、系統或交付物字面；目前 promotion 沒有抽到時保持空值
	ObjectText string `json:"object_text,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TodoQuery when eager-loading is set.
	Edges        TodoEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TodoEdges holds the relations/edges for other nodes in the graph.
type TodoEdges struct {
	// 正式待辦所屬 channel
	Channel *Channel `json:"channel,omitempty"`
	// 此待辦所屬使用者；同一個 candidate 若指派多人，會 promotion 成多筆不同 owner 的 Todo
	Owner *User `json:"owner,omitempty"`
	// AI promotion 來源；只保存分析/evidence 關聯，不作為 Todo 五要素的主要讀取來源
	SourceCandidate *TodoCandidate `json:"source_candidate,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
	// totalCount holds the count of the edges above.
	totalCount [3]map[string]int
}

// ChannelOrErr returns the Channel value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TodoEdges) ChannelOrErr() (*Channel, error) {
	if e.Channel != nil {
		return e.Channel, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: channel.Label}
	}
	return nil, &NotLoadedError{edge: "channel"}
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TodoEdges) OwnerOrErr() (*User, error) {
	if e.Owner != nil {
		return e.Owner, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// SourceCandidateOrErr returns the SourceCandidate value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TodoEdges) SourceCandidateOrErr() (*TodoCandidate, error) {
	if e.SourceCandidate != nil {
		return e.SourceCandidate, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: todocandidate.Label}
	}
	return nil, &NotLoadedError{edge: "source_candidate"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Todo) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case todo.FieldSourceCandidateID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case todo.FieldStatus, todo.FieldTitle, todo.FieldDueTimezone, todo.FieldDuePrecision, todo.FieldLocationText, todo.FieldObjectText:
			values[i] = new(sql.NullString)
		case todo.FieldCreatedAt, todo.FieldUpdatedAt, todo.FieldDueAt:
			values[i] = new(sql.NullTime)
		case todo.FieldID, todo.FieldChannelID, todo.FieldOwnerUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Todo fields.
func (_m *Todo) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case todo.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case todo.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case todo.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case todo.FieldChannelID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field channel_id", values[i])
			} else if value != nil {
				_m.ChannelID = *value
			}
		case todo.FieldOwnerUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field owner_user_id", values[i])
			} else if value != nil {
				_m.OwnerUserID = *value
			}
		case todo.FieldSourceCandidateID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field source_candidate_id", values[i])
			} else if value.Valid {
				_m.SourceCandidateID = new(uuid.UUID)
				*_m.SourceCandidateID = *value.S.(*uuid.UUID)
			}
		case todo.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = todo.Status(value.String)
			}
		case todo.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case todo.FieldDueAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field due_at", values[i])
			} else if value.Valid {
				_m.DueAt = new(time.Time)
				*_m.DueAt = value.Time
			}
		case todo.FieldDueTimezone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field due_timezone", values[i])
			} else if value.Valid {
				_m.DueTimezone = value.String
			}
		case todo.FieldDuePrecision:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field due_precision", values[i])
			} else if value.Valid {
				_m.DuePrecision = todo.DuePrecision(value.String)
			}
		case todo.FieldLocationText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field location_text", values[i])
			} else if value.Valid {
				_m.LocationText = value.String
			}
		case todo.FieldObjectText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field object_text", values[i])
			} else if value.Valid {
				_m.ObjectText = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Todo.
// This includes values selected through modifiers, order, etc.
func (_m *Todo) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryChannel queries the "channel" edge of the Todo entity.
func (_m *Todo) QueryChannel() *ChannelQuery {
	return NewTodoClient(_m.config).QueryChannel(_m)
}

// QueryOwner queries the "owner" edge of the Todo entity.
func (_m *Todo) QueryOwner() *UserQuery {
	return NewTodoClient(_m.config).QueryOwner(_m)
}

// QuerySourceCandidate queries the "source_candidate" edge of the Todo entity.
func (_m *Todo) QuerySourceCandidate() *TodoCandidateQuery {
	return NewTodoClient(_m.config).QuerySourceCandidate(_m)
}

// Update returns a builder for updating this Todo.
// Note that you need to call Todo.Unwrap() before calling this method if this Todo
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Todo) Update() *TodoUpdateOne {
	return NewTodoClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Todo entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Todo) Unwrap() *Todo {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Todo is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Todo) String() string {
	var builder strings.Builder
	builder.WriteString("Todo(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("channel_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChannelID))
	builder.WriteString(", ")
	builder.WriteString("owner_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OwnerUserID))
	builder.WriteString(", ")
	if v := _m.SourceCandidateID; v != nil {
		builder.WriteString("source_candidate_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	if v := _m.DueAt; v != nil {
		builder.WriteString("due_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("due_timezone=")
	builder.WriteString(_m.DueTimezone)
	builder.WriteString(", ")
	builder.WriteString("due_precision=")
	builder.WriteString(fmt.Sprintf("%v", _m.DuePrecision))
	builder.WriteString(", ")
	builder.WriteString("location_text=")
	builder.WriteString(_m.LocationText)
	builder.WriteString(", ")
	builder.WriteString("object_text=")
	builder.WriteString(_m.ObjectText)
	builder.WriteByte(')')
	return builder.String()
}

// Todos is a parsable slice of Todo.
type Todos []*Todo
