// Code generated by ent, DO NOT EDIT.

package ent

import (
	"assistant-api/internal/ent/channelmessage"
	"assistant-api/internal/ent/predicate"
	"assistant-api/internal/ent/todo"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// TodoUpdate is the builder for updating Todo entities.
type TodoUpdate struct {
	config
	hooks    []Hook
	mutation *TodoMutation
}

// Where appends a list predicates to the TodoUpdate builder.
func (_u *TodoUpdate) Where(ps ...predicate.Todo) *TodoUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TodoUpdate) SetUpdatedAt(v time.Time) *TodoUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetLastMessageID sets the "last_message_id" field.
func (_u *TodoUpdate) SetLastMessageID(v uuid.UUID) *TodoUpdate {
	_u.mutation.SetLastMessageID(v)
	return _u
}

// SetNillableLastMessageID sets the "last_message_id" field if the given value is not nil.
func (_u *TodoUpdate) SetNillableLastMessageID(v *uuid.UUID) *TodoUpdate {
	if v != nil {
		_u.SetLastMessageID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TodoUpdate) SetStatus(v todo.Status) *TodoUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TodoUpdate) SetNillableStatus(v *todo.Status) *TodoUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *TodoUpdate) SetTitle(v string) *TodoUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *TodoUpdate) SetNillableTitle(v *string) *TodoUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetAssignees sets the "assignees" field.
func (_u *TodoUpdate) SetAssignees(v []string) *TodoUpdate {
	_u.mutation.SetAssignees(v)
	return _u
}

// AppendAssignees appends value to the "assignees" field.
func (_u *TodoUpdate) AppendAssignees(v []string) *TodoUpdate {
	_u.mutation.AppendAssignees(v)
	return _u
}

// ClearAssignees clears the value of the "assignees" field.
func (_u *TodoUpdate) ClearAssignees() *TodoUpdate {
	_u.mutation.ClearAssignees()
	return _u
}

// SetDueAt sets the "due_at" field.
func (_u *TodoUpdate) SetDueAt(v time.Time) *TodoUpdate {
	_u.mutation.SetDueAt(v)
	return _u
}

// SetNillableDueAt sets the "due_at" field if the given value is not nil.
func (_u *TodoUpdate) SetNillableDueAt(v *time.Time) *TodoUpdate {
	if v != nil {
		_u.SetDueAt(*v)
	}
	return _u
}

// SetDueTimezone sets the "due_timezone" field.
func (_u *TodoUpdate) SetDueTimezone(v string) *TodoUpdate {
	_u.mutation.SetDueTimezone(v)
	return _u
}

// SetNillableDueTimezone sets the "due_timezone" field if the given value is not nil.
func (_u *TodoUpdate) SetNillableDueTimezone(v *string) *TodoUpdate {
	if v != nil {
		_u.SetDueTimezone(*v)
	}
	return _u
}

// SetDuePrecision sets the "due_precision" field.
func (_u *TodoUpdate) SetDuePrecision(v todo.DuePrecision) *TodoUpdate {
	_u.mutation.SetDuePrecision(v)
	return _u
}

// SetNillableDuePrecision sets the "due_precision" field if the given value is not nil.
func (_u *TodoUpdate) SetNillableDuePrecision(v *todo.DuePrecision) *TodoUpdate {
	if v != nil {
		_u.SetDuePrecision(*v)
	}
	return _u
}

// SetConfidence sets the "confidence" field.
func (_u *TodoUpdate) SetConfidence(v float64) *TodoUpdate {
	_u.mutation.ResetConfidence()
	_u.mutation.SetConfidence(v)
	return _u
}

// SetNillableConfidence sets the "confidence" field if the given value is not nil.
func (_u *TodoUpdate) SetNillableConfidence(v *float64) *TodoUpdate {
	if v != nil {
		_u.SetConfidence(*v)
	}
	return _u
}

// AddConfidence adds value to the "confidence" field.
func (_u *TodoUpdate) AddConfidence(v float64) *TodoUpdate {
	_u.mutation.AddConfidence(v)
	return _u
}

// SetPromotionReason sets the "promotion_reason" field.
func (_u *TodoUpdate) SetPromotionReason(v string) *TodoUpdate {
	_u.mutation.SetPromotionReason(v)
	return _u
}

// SetNillablePromotionReason sets the "promotion_reason" field if the given value is not nil.
func (_u *TodoUpdate) SetNillablePromotionReason(v *string) *TodoUpdate {
	if v != nil {
		_u.SetPromotionReason(*v)
	}
	return _u
}

// ClearPromotionReason clears the value of the "promotion_reason" field.
func (_u *TodoUpdate) ClearPromotionReason() *TodoUpdate {
	_u.mutation.ClearPromotionReason()
	return _u
}

// SetLastMessage sets the "last_message" edge to the ChannelMessage entity.
func (_u *TodoUpdate) SetLastMessage(v *ChannelMessage) *TodoUpdate {
	return _u.SetLastMessageID(v.ID)
}

// Mutation returns the TodoMutation object of the builder.
func (_u *TodoUpdate) Mutation() *TodoMutation {
	return _u.mutation
}

// ClearLastMessage clears the "last_message" edge to the ChannelMessage entity.
func (_u *TodoUpdate) ClearLastMessage() *TodoUpdate {
	_u.mutation.ClearLastMessage()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TodoUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TodoUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TodoUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TodoUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TodoUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := todo.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TodoUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := todo.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Todo.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DuePrecision(); ok {
		if err := todo.DuePrecisionValidator(v); err != nil {
			return &ValidationError{Name: "due_precision", err: fmt.Errorf(`ent: validator failed for field "Todo.due_precision": %w`, err)}
		}
	}
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Todo.channel"`)
	}
	if _u.mutation.SourceCandidateCleared() && len(_u.mutation.SourceCandidateIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Todo.source_candidate"`)
	}
	if _u.mutation.SourceMessageCleared() && len(_u.mutation.SourceMessageIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Todo.source_message"`)
	}
	if _u.mutation.LastMessageCleared() && len(_u.mutation.LastMessageIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Todo.last_message"`)
	}
	return nil
}

func (_u *TodoUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(todo.Table, todo.Columns, sqlgraph.NewFieldSpec(todo.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(todo.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(todo.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(todo.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Assignees(); ok {
		_spec.SetField(todo.FieldAssignees, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAssignees(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, todo.FieldAssignees, value)
		})
	}
	if _u.mutation.AssigneesCleared() {
		_spec.ClearField(todo.FieldAssignees, field.TypeJSON)
	}
	if value, ok := _u.mutation.DueAt(); ok {
		_spec.SetField(todo.FieldDueAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DueTimezone(); ok {
		_spec.SetField(todo.FieldDueTimezone, field.TypeString, value)
	}
	if value, ok := _u.mutation.DuePrecision(); ok {
		_spec.SetField(todo.FieldDuePrecision, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Confidence(); ok {
		_spec.SetField(todo.FieldConfidence, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedConfidence(); ok {
		_spec.AddField(todo.FieldConfidence, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PromotionReason(); ok {
		_spec.SetField(todo.FieldPromotionReason, field.TypeString, value)
	}
	if _u.mutation.PromotionReasonCleared() {
		_spec.ClearField(todo.FieldPromotionReason, field.TypeString)
	}
	if _u.mutation.LastMessageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   todo.LastMessageTable,
			Columns: []string{todo.LastMessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelmessage.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LastMessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   todo.LastMessageTable,
			Columns: []string{todo.LastMessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelmessage.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{todo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TodoUpdateOne is the builder for updating a single Todo entity.
type TodoUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TodoMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TodoUpdateOne) SetUpdatedAt(v time.Time) *TodoUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetLastMessageID sets the "last_message_id" field.
func (_u *TodoUpdateOne) SetLastMessageID(v uuid.UUID) *TodoUpdateOne {
	_u.mutation.SetLastMessageID(v)
	return _u
}

// SetNillableLastMessageID sets the "last_message_id" field if the given value is not nil.
func (_u *TodoUpdateOne) SetNillableLastMessageID(v *uuid.UUID) *TodoUpdateOne {
	if v != nil {
		_u.SetLastMessageID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TodoUpdateOne) SetStatus(v todo.Status) *TodoUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TodoUpdateOne) SetNillableStatus(v *todo.Status) *TodoUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *TodoUpdateOne) SetTitle(v string) *TodoUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *TodoUpdateOne) SetNillableTitle(v *string) *TodoUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetAssignees sets the "assignees" field.
func (_u *TodoUpdateOne) SetAssignees(v []string) *TodoUpdateOne {
	_u.mutation.SetAssignees(v)
	return _u
}

// AppendAssignees appends value to the "assignees" field.
func (_u *TodoUpdateOne) AppendAssignees(v []string) *TodoUpdateOne {
	_u.mutation.AppendAssignees(v)
	return _u
}

// ClearAssignees clears the value of the "assignees" field.
func (_u *TodoUpdateOne) ClearAssignees() *TodoUpdateOne {
	_u.mutation.ClearAssignees()
	return _u
}

// SetDueAt sets the "due_at" field.
func (_u *TodoUpdateOne) SetDueAt(v time.Time) *TodoUpdateOne {
	_u.mutation.SetDueAt(v)
	return _u
}

// SetNillableDueAt sets the "due_at" field if the given value is not nil.
func (_u *TodoUpdateOne) SetNillableDueAt(v *time.Time) *TodoUpdateOne {
	if v != nil {
		_u.SetDueAt(*v)
	}
	return _u
}

// SetDueTimezone sets the "due_timezone" field.
func (_u *TodoUpdateOne) SetDueTimezone(v string) *TodoUpdateOne {
	_u.mutation.SetDueTimezone(v)
	return _u
}

// SetNillableDueTimezone sets the "due_timezone" field if the given value is not nil.
func (_u *TodoUpdateOne) SetNillableDueTimezone(v *string) *TodoUpdateOne {
	if v != nil {
		_u.SetDueTimezone(*v)
	}
	return _u
}

// SetDuePrecision sets the "due_precision" field.
func (_u *TodoUpdateOne) SetDuePrecision(v todo.DuePrecision) *TodoUpdateOne {
	_u.mutation.SetDuePrecision(v)
	return _u
}

// SetNillableDuePrecision sets the "due_precision" field if the given value is not nil.
func (_u *TodoUpdateOne) SetNillableDuePrecision(v *todo.DuePrecision) *TodoUpdateOne {
	if v != nil {
		_u.SetDuePrecision(*v)
	}
	return _u
}

// SetConfidence sets the "confidence" field.
func (_u *TodoUpdateOne) SetConfidence(v float64) *TodoUpdateOne {
	_u.mutation.ResetConfidence()
	_u.mutation.SetConfidence(v)
	return _u
}

// SetNillableConfidence sets the "confidence" field if the given value is not nil.
func (_u *TodoUpdateOne) SetNillableConfidence(v *float64) *TodoUpdateOne {
	if v != nil {
		_u.SetConfidence(*v)
	}
	return _u
}

// AddConfidence adds value to the "confidence" field.
func (_u *TodoUpdateOne) AddConfidence(v float64) *TodoUpdateOne {
	_u.mutation.AddConfidence(v)
	return _u
}

// SetPromotionReason sets the "promotion_reason" field.
func (_u *TodoUpdateOne) SetPromotionReason(v string) *TodoUpdateOne {
	_u.mutation.SetPromotionReason(v)
	return _u
}

// SetNillablePromotionReason sets the "promotion_reason" field if the given value is not nil.
func (_u *TodoUpdateOne) SetNillablePromotionReason(v *string) *TodoUpdateOne {
	if v != nil {
		_u.SetPromotionReason(*v)
	}
	return _u
}

// ClearPromotionReason clears the value of the "promotion_reason" field.
func (_u *TodoUpdateOne) ClearPromotionReason() *TodoUpdateOne {
	_u.mutation.ClearPromotionReason()
	return _u
}

// SetLastMessage sets the "last_message" edge to the ChannelMessage entity.
func (_u *TodoUpdateOne) SetLastMessage(v *ChannelMessage) *TodoUpdateOne {
	return _u.SetLastMessageID(v.ID)
}

// Mutation returns the TodoMutation object of the builder.
func (_u *TodoUpdateOne) Mutation() *TodoMutation {
	return _u.mutation
}

// ClearLastMessage clears the "last_message" edge to the ChannelMessage entity.
func (_u *TodoUpdateOne) ClearLastMessage() *TodoUpdateOne {
	_u.mutation.ClearLastMessage()
	return _u
}

// Where appends a list predicates to the TodoUpdate builder.
func (_u *TodoUpdateOne) Where(ps ...predicate.Todo) *TodoUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TodoUpdateOne) Select(field string, fields ...string) *TodoUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Todo entity.
func (_u *TodoUpdateOne) Save(ctx context.Context) (*Todo, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TodoUpdateOne) SaveX(ctx context.Context) *Todo {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TodoUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TodoUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TodoUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := todo.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TodoUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := todo.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Todo.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DuePrecision(); ok {
		if err := todo.DuePrecisionValidator(v); err != nil {
			return &ValidationError{Name: "due_precision", err: fmt.Errorf(`ent: validator failed for field "Todo.due_precision": %w`, err)}
		}
	}
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Todo.channel"`)
	}
	if _u.mutation.SourceCandidateCleared() && len(_u.mutation.SourceCandidateIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Todo.source_candidate"`)
	}
	if _u.mutation.SourceMessageCleared() && len(_u.mutation.SourceMessageIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Todo.source_message"`)
	}
	if _u.mutation.LastMessageCleared() && len(_u.mutation.LastMessageIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Todo.last_message"`)
	}
	return nil
}

func (_u *TodoUpdateOne) sqlSave(ctx context.Context) (_node *Todo, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(todo.Table, todo.Columns, sqlgraph.NewFieldSpec(todo.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Todo.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, todo.FieldID)
		for _, f := range fields {
			if !todo.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != todo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(todo.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(todo.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(todo.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Assignees(); ok {
		_spec.SetField(todo.FieldAssignees, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAssignees(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, todo.FieldAssignees, value)
		})
	}
	if _u.mutation.AssigneesCleared() {
		_spec.ClearField(todo.FieldAssignees, field.TypeJSON)
	}
	if value, ok := _u.mutation.DueAt(); ok {
		_spec.SetField(todo.FieldDueAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DueTimezone(); ok {
		_spec.SetField(todo.FieldDueTimezone, field.TypeString, value)
	}
	if value, ok := _u.mutation.DuePrecision(); ok {
		_spec.SetField(todo.FieldDuePrecision, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Confidence(); ok {
		_spec.SetField(todo.FieldConfidence, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedConfidence(); ok {
		_spec.AddField(todo.FieldConfidence, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PromotionReason(); ok {
		_spec.SetField(todo.FieldPromotionReason, field.TypeString, value)
	}
	if _u.mutation.PromotionReasonCleared() {
		_spec.ClearField(todo.FieldPromotionReason, field.TypeString)
	}
	if _u.mutation.LastMessageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   todo.LastMessageTable,
			Columns: []string{todo.LastMessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelmessage.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LastMessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   todo.LastMessageTable,
			Columns: []string{todo.LastMessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelmessage.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Todo{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{todo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
