// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Action is the predicate function for action builders.
type Action func(*sql.Selector)

// ActionResult is the predicate function for actionresult builders.
type ActionResult func(*sql.Selector)

// ActionRoute is the predicate function for actionroute builders.
type ActionRoute func(*sql.Selector)

// Channel is the predicate function for channel builders.
type Channel func(*sql.Selector)

// ChannelMessage is the predicate function for channelmessage builders.
type ChannelMessage func(*sql.Selector)

// ChannelMessageMention is the predicate function for channelmessagemention builders.
type ChannelMessageMention func(*sql.Selector)

// ChannelServiceMember is the predicate function for channelservicemember builders.
type ChannelServiceMember func(*sql.Selector)

// Line is the predicate function for line builders.
type Line func(*sql.Selector)

// Skill is the predicate function for skill builders.
type Skill func(*sql.Selector)

// Slack is the predicate function for slack builders.
type Slack func(*sql.Selector)

// SlackWorkspace is the predicate function for slackworkspace builders.
type SlackWorkspace func(*sql.Selector)

// TodoCandidate is the predicate function for todocandidate builders.
type TodoCandidate func(*sql.Selector)

// TodoCandidateAssignee is the predicate function for todocandidateassignee builders.
type TodoCandidateAssignee func(*sql.Selector)

// TranslationLocale is the predicate function for translationlocale builders.
type TranslationLocale func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
