run_mode: "dev"

log:
    level: "info"
    filename: ""
    max_size: 10
    max_age: 7
    max_backups: 5

server:
    port: "8080"

database:
    auto_schema_create: true

postgresql:
    address: "127.0.0.1:5432"
    database: "assistant_dev2"
    user_name: "postgres"
    password: "d22340014"
    parameters: "sslmode=disable"

graphql:
    query_path: "/query"
    playground_path: "/playground"
