run_mode: "dev"

log:
    level: "info"
    filename: ""
    max_size: 10
    max_age: 7
    max_backups: 5

server:
    port: "8080"
ai:
    semantic_decision_service_url: "http://127.0.0.1:9002"
    semantic_decision_service_timeout_seconds: 90
    embedding_url: "http://127.0.0.1:9000"
    embedding_timeout_seconds: 60
    embedding_path: "/embed"
database:
    auto_schema_create: true

postgresql:
    address: "127.0.0.1:5432"
    database: "assistant_dev2"
    user_name: "postgres"
    password: "d22340014"
    parameters: "sslmode=disable"

line:
    channel_token: "nyIJ/34bQBdUCMDt4qnZHMUMTacR0r4d6DC8DZRbEemdkh2jn+pJdz6b8ID3znqivrpU9VMM6r+Vb+s5R4wJoayE5Ndux1lk2JxzuqlTNEotrhZ9qfnS2huRjmPLb4iUykRggJ3Xr71QPynULjAb1AdB04t89/1O/w1cDnyilFU="
    channel_secret: "7966f875a2c3c7bcf8a22a27b048d524"
    channel_id: "2009014065"
    bot_user_id: "U020a927b2f6a423a66c488acc29f1b6e"
    client_secret: "5f53fccaf3589b484652412c1970a431"
    redirect_uri: "https://uninebriated-nonexplorative-kasey.ngrok-free.dev/line/bind"
    assistant_bot_url: "https://line.me/R/ti/p/@001ondgw"
    scopes: "openid profile email"

graphql:
    query_path: "/query"
    playground_path: "/playground"
