// Code generated by ent, DO NOT EDIT.

package actionsuccessmessage

import (
	"assistant-api/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ActionSuccessMessage {
	return predicate.ActionSuccessMessage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ActionSuccessMessage {
	return predicate.ActionSuccessMessage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ActionSuccessMessage {
	return predicate.ActionSuccessMessage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ActionSuccessMessage {
	return predicate.ActionSuccessMessage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ActionSuccessMessage {
	return predicate.ActionSuccessMessage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ActionSuccessMessage {
	return predicate.ActionSuccessMessage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ActionSuccessMessage {
	return predicate.ActionSuccessMessage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ActionSuccessMessage {
	return predicate.ActionSuccessMessage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ActionSuccessMessage {
	return predicate.ActionSuccessMessage(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ActionSuccessMessage {
	return predicate.ActionSuccessMessage(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ActionSuccessMessage {
	return predicate.ActionSuccessMessage(sql.FieldEQ(FieldUpdatedAt, v))
}

// ActionID applies equality check predicate on the "action_id" field. It's identical to ActionIDEQ.
func ActionID(v uuid.UUID) predicate.ActionSuccessMessage {
	return predicate.ActionSuccessMessage(sql.FieldEQ(FieldActionID, v))
}

// ChannelMessageID applies equality check predicate on the "channel_message_id" field. It's identical to ChannelMessageIDEQ.
func ChannelMessageID(v uuid.UUID) predicate.ActionSuccessMessage {
	return predicate.ActionSuccessMessage(sql.FieldEQ(FieldChannelMessageID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ActionSuccessMessage {
	return predicate.ActionSuccessMessage(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ActionSuccessMessage {
	return predicate.ActionSuccessMessage(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ActionSuccessMessage {
	return predicate.ActionSuccessMessage(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ActionSuccessMessage {
	return predicate.ActionSuccessMessage(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ActionSuccessMessage {
	return predicate.ActionSuccessMessage(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ActionSuccessMessage {
	return predicate.ActionSuccessMessage(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ActionSuccessMessage {
	return predicate.ActionSuccessMessage(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ActionSuccessMessage {
	return predicate.ActionSuccessMessage(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ActionSuccessMessage {
	return predicate.ActionSuccessMessage(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ActionSuccessMessage {
	return predicate.ActionSuccessMessage(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ActionSuccessMessage {
	return predicate.ActionSuccessMessage(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ActionSuccessMessage {
	return predicate.ActionSuccessMessage(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ActionSuccessMessage {
	return predicate.ActionSuccessMessage(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ActionSuccessMessage {
	return predicate.ActionSuccessMessage(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ActionSuccessMessage {
	return predicate.ActionSuccessMessage(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ActionSuccessMessage {
	return predicate.ActionSuccessMessage(sql.FieldLTE(FieldUpdatedAt, v))
}

// ActionIDEQ applies the EQ predicate on the "action_id" field.
func ActionIDEQ(v uuid.UUID) predicate.ActionSuccessMessage {
	return predicate.ActionSuccessMessage(sql.FieldEQ(FieldActionID, v))
}

// ActionIDNEQ applies the NEQ predicate on the "action_id" field.
func ActionIDNEQ(v uuid.UUID) predicate.ActionSuccessMessage {
	return predicate.ActionSuccessMessage(sql.FieldNEQ(FieldActionID, v))
}

// ActionIDIn applies the In predicate on the "action_id" field.
func ActionIDIn(vs ...uuid.UUID) predicate.ActionSuccessMessage {
	return predicate.ActionSuccessMessage(sql.FieldIn(FieldActionID, vs...))
}

// ActionIDNotIn applies the NotIn predicate on the "action_id" field.
func ActionIDNotIn(vs ...uuid.UUID) predicate.ActionSuccessMessage {
	return predicate.ActionSuccessMessage(sql.FieldNotIn(FieldActionID, vs...))
}

// ChannelMessageIDEQ applies the EQ predicate on the "channel_message_id" field.
func ChannelMessageIDEQ(v uuid.UUID) predicate.ActionSuccessMessage {
	return predicate.ActionSuccessMessage(sql.FieldEQ(FieldChannelMessageID, v))
}

// ChannelMessageIDNEQ applies the NEQ predicate on the "channel_message_id" field.
func ChannelMessageIDNEQ(v uuid.UUID) predicate.ActionSuccessMessage {
	return predicate.ActionSuccessMessage(sql.FieldNEQ(FieldChannelMessageID, v))
}

// ChannelMessageIDIn applies the In predicate on the "channel_message_id" field.
func ChannelMessageIDIn(vs ...uuid.UUID) predicate.ActionSuccessMessage {
	return predicate.ActionSuccessMessage(sql.FieldIn(FieldChannelMessageID, vs...))
}

// ChannelMessageIDNotIn applies the NotIn predicate on the "channel_message_id" field.
func ChannelMessageIDNotIn(vs ...uuid.UUID) predicate.ActionSuccessMessage {
	return predicate.ActionSuccessMessage(sql.FieldNotIn(FieldChannelMessageID, vs...))
}

// HasAction applies the HasEdge predicate on the "action" edge.
func HasAction() predicate.ActionSuccessMessage {
	return predicate.ActionSuccessMessage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ActionTable, ActionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasActionWith applies the HasEdge predicate on the "action" edge with a given conditions (other predicates).
func HasActionWith(preds ...predicate.Action) predicate.ActionSuccessMessage {
	return predicate.ActionSuccessMessage(func(s *sql.Selector) {
		step := newActionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasChannelMessage applies the HasEdge predicate on the "channel_message" edge.
func HasChannelMessage() predicate.ActionSuccessMessage {
	return predicate.ActionSuccessMessage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ChannelMessageTable, ChannelMessageColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChannelMessageWith applies the HasEdge predicate on the "channel_message" edge with a given conditions (other predicates).
func HasChannelMessageWith(preds ...predicate.ChannelMessage) predicate.ActionSuccessMessage {
	return predicate.ActionSuccessMessage(func(s *sql.Selector) {
		step := newChannelMessageStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ActionSuccessMessage) predicate.ActionSuccessMessage {
	return predicate.ActionSuccessMessage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ActionSuccessMessage) predicate.ActionSuccessMessage {
	return predicate.ActionSuccessMessage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ActionSuccessMessage) predicate.ActionSuccessMessage {
	return predicate.ActionSuccessMessage(sql.NotPredicates(p))
}
