package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.68

import (
	"assistant-api/internal/config"
	"assistant-api/internal/ent"
	"assistant-api/internal/ent/channel"
	"assistant-api/internal/ent/channelmessage"
	"assistant-api/internal/graph/model"
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"github.com/google/uuid"
)

// SimulateLineTodoConversation is the resolver for the simulateLineTodoConversation field.
func (r *mutationResolver) SimulateLineTodoConversation(ctx context.Context, input model.SimulateLineTodoConversationInput) (*model.SimulateLineTodoConversationPayload, error) {
	if !strings.EqualFold(strings.TrimSpace(config.RunMode), "dev") {
		return nil, fmt.Errorf("simulateLineTodoConversation is only available in dev run mode")
	}
	if r == nil || r.Client == nil {
		return nil, fmt.Errorf("ent client is not initialized")
	}
	if r.LinePushInitErr != nil || r.LinePushService == nil {
		return nil, fmt.Errorf("line messaging is not configured")
	}
	if r.LineWebhookProcessor == nil {
		return nil, fmt.Errorf("line webhook processor is not initialized")
	}

	if input.ChannelID == uuid.Nil {
		return nil, fmt.Errorf("channelID is required")
	}
	if input.ParticipantCount < 2 {
		return nil, fmt.Errorf("participantCount must be at least 2")
	}
	if input.MessageCount < input.ParticipantCount {
		return nil, fmt.Errorf("messageCount must be greater than or equal to participantCount")
	}

	ch, err := r.Client.Channel.Get(ctx, input.ChannelID)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, fmt.Errorf("channel is not found: %s", input.ChannelID.String())
		}
		return nil, fmt.Errorf("query channel failed: %w", err)
	}
	if ch.Platform != channel.PlatformLine {
		return nil, fmt.Errorf("channel must be a line channel")
	}
	if ch.Type != channel.TypeGroup {
		return nil, fmt.Errorf("line channel must be a group channel")
	}
	lineChannelID := strings.TrimSpace(ch.GroupID)
	if lineChannelID == "" {
		return nil, fmt.Errorf("line channel group id is empty")
	}

	participants, err := r.pickRandomLineParticipants(ctx, input.ParticipantCount)
	if err != nil {
		return nil, err
	}

	messages := make([]*model.SimulatedLineTodoMessage, 0, input.MessageCount)
	for index := 0; index < input.MessageCount; index++ {
		participant := participants[index%len(participants)]
		text := buildCasualTodoSimulationText(index, participants)
		platformMessageID := "dev-line-todo-" + uuid.NewString()
		timestamp := time.Now().UnixMilli()

		body, err := json.Marshal(simulatedLineWebhookBody{Events: []simulatedLineWebhookEvent{{
			Type: "message",
			Source: simulatedLineWebhookSource{
				Type:    "group",
				UserID:  participant.LineUserID,
				GroupID: lineChannelID,
			},
			Message: simulatedLineWebhookMessage{
				ID:   platformMessageID,
				Type: "text",
				Text: text,
			},
			Timestamp: timestamp,
		}}})
		if err != nil {
			return nil, fmt.Errorf("marshal simulated line webhook failed: %w", err)
		}

		r.LineWebhookProcessor.ProcessIncoming(body, "dev-simulation")

		lineText := participant.Name + "：" + text
		sentLineMessageID, err := r.LinePushService.SendTextToChat(ctx, lineChannelID, "", lineText, "", "")
		if err != nil {
			return nil, fmt.Errorf("send simulated message to line failed: %w", err)
		}

		var savedMessageID *uuid.UUID
		if saved, err := r.Client.ChannelMessage.Query().Where(channelmessage.ChannelIDEQ(ch.ID), channelmessage.PlatformMessageIDEQ(platformMessageID)).Only(ctx); err != nil {
			if !ent.IsNotFound(err) {
				return nil, fmt.Errorf("query saved simulated message failed: %w", err)
			}
		} else {
			savedMessageID = &saved.ID
		}

		messages = append(messages, &model.SimulatedLineTodoMessage{
			SpeakerUserID:     participant.UserID,
			LineUserID:        participant.LineUserID,
			DisplayName:       participant.Name,
			Text:              text,
			LineText:          lineText,
			PlatformMessageID: platformMessageID,
			SavedMessageID:    savedMessageID,
			SentLineMessageID: &sentLineMessageID,
		})
	}

	payloadParticipants := make([]*model.SimulatedLineTodoParticipant, 0, len(participants))
	for _, participant := range participants {
		payloadParticipants = append(payloadParticipants, &model.SimulatedLineTodoParticipant{
			UserID:      participant.UserID,
			LineUserID:  participant.LineUserID,
			DisplayName: participant.Name,
		})
	}

	return &model.SimulateLineTodoConversationPayload{
		Status:        "sent",
		ChannelID:     ch.ID,
		LineChannelID: lineChannelID,
		Participants:  payloadParticipants,
		Messages:      messages,
	}, nil
}

// ClearDevRealtimeTodoData is the resolver for the clearDevRealtimeTodoData field.
//
// 用途：開發時清空實時 Todo 流程產生的測試資料，方便重複測試實時分析/挑治流程而不用手動清 DB。
// 僅允許在 dev run mode 執行，避免誤操作清空正式環境資料。
func (r *mutationResolver) ClearDevRealtimeTodoData(ctx context.Context) (*model.ClearDevRealtimeTodoDataPayload, error) {
	if !strings.EqualFold(strings.TrimSpace(config.RunMode), "dev") {
		return nil, fmt.Errorf("clearDevRealtimeTodoData is only available in dev run mode")
	}
	if r == nil || r.Client == nil {
		return nil, fmt.Errorf("ent client is not initialized")
	}

	// 刪除順序必須順著外鍵依賴方向從「葉節點」往「上游」刪，否則會因子資料尚存在而卡在外鍵限制：
	// action_result 參照 channel_message；todo_event/todo_update_candidate 參照正式 Todo，也可能參照 candidate/message；
	// todo_candidate_assignee/todo_candidate_evidence_message 參照 todo_candidate；channel_message_mention 與 evidence 也會參照 channel_message，
	// 因此最後才能刪 todo_candidate 與 channel_message。
	actionResultCount, err := r.Client.ActionResult.Delete().Exec(ctx)
	if err != nil {
		return nil, fmt.Errorf("delete action results failed: %w", err)
	}
	todoEventCount, err := r.Client.TodoEvent.Delete().Exec(ctx)
	if err != nil {
		return nil, fmt.Errorf("delete todo events failed: %w", err)
	}
	todoUpdateCandidateCount, err := r.Client.TodoUpdateCandidate.Delete().Exec(ctx)
	if err != nil {
		return nil, fmt.Errorf("delete todo update candidates failed: %w", err)
	}
	todoCount, err := r.Client.Todo.Delete().Exec(ctx)
	if err != nil {
		return nil, fmt.Errorf("delete todos failed: %w", err)
	}
	todoCandidateAssigneeCount, err := r.Client.TodoCandidateAssignee.Delete().Exec(ctx)
	if err != nil {
		return nil, fmt.Errorf("delete todo candidate assignees failed: %w", err)
	}
	todoCandidateEvidenceMessageCount, err := r.Client.TodoCandidateEvidenceMessage.Delete().Exec(ctx)
	if err != nil {
		return nil, fmt.Errorf("delete todo candidate evidence messages failed: %w", err)
	}
	channelMessageMentionCount, err := r.Client.ChannelMessageMention.Delete().Exec(ctx)
	if err != nil {
		return nil, fmt.Errorf("delete channel message mentions failed: %w", err)
	}
	todoCandidateCount, err := r.Client.TodoCandidate.Delete().Exec(ctx)
	if err != nil {
		return nil, fmt.Errorf("delete todo candidates failed: %w", err)
	}
	channelMessageCount, err := r.Client.ChannelMessage.Delete().Exec(ctx)
	if err != nil {
		return nil, fmt.Errorf("delete channel messages failed: %w", err)
	}

	// 回傳每種實體實際被刪除的筆數，方便呼叫端（開發工具）確認清空範圍與結果。
	return &model.ClearDevRealtimeTodoDataPayload{
		Status:                            "cleared",
		TodoCount:                         todoCount,
		TodoEventCount:                    todoEventCount,
		TodoUpdateCandidateCount:          todoUpdateCandidateCount,
		ChannelMessageCount:               channelMessageCount,
		TodoCandidateCount:                todoCandidateCount,
		TodoCandidateEvidenceMessageCount: todoCandidateEvidenceMessageCount,
		TodoCandidateAssigneeCount:        todoCandidateAssigneeCount,
		ChannelMessageMentionCount:        channelMessageMentionCount,
		ActionResultCount:                 actionResultCount,
	}, nil
}
