// Code generated by ent, DO NOT EDIT.

package slack

import (
	"assistant-api/internal/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Slack {
	return predicate.Slack(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Slack {
	return predicate.Slack(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Slack {
	return predicate.Slack(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Slack {
	return predicate.Slack(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Slack {
	return predicate.Slack(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Slack {
	return predicate.Slack(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Slack {
	return predicate.Slack(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Slack {
	return predicate.Slack(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Slack {
	return predicate.Slack(sql.FieldLTE(FieldID, id))
}

// TeamID applies equality check predicate on the "team_id" field. It's identical to TeamIDEQ.
func TeamID(v string) predicate.Slack {
	return predicate.Slack(sql.FieldEQ(FieldTeamID, v))
}

// SlackUserID applies equality check predicate on the "slack_user_id" field. It's identical to SlackUserIDEQ.
func SlackUserID(v string) predicate.Slack {
	return predicate.Slack(sql.FieldEQ(FieldSlackUserID, v))
}

// DisplayName applies equality check predicate on the "display_name" field. It's identical to DisplayNameEQ.
func DisplayName(v string) predicate.Slack {
	return predicate.Slack(sql.FieldEQ(FieldDisplayName, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.Slack {
	return predicate.Slack(sql.FieldEQ(FieldEmail, v))
}

// Picture applies equality check predicate on the "picture" field. It's identical to PictureEQ.
func Picture(v string) predicate.Slack {
	return predicate.Slack(sql.FieldEQ(FieldPicture, v))
}

// TeamIDEQ applies the EQ predicate on the "team_id" field.
func TeamIDEQ(v string) predicate.Slack {
	return predicate.Slack(sql.FieldEQ(FieldTeamID, v))
}

// TeamIDNEQ applies the NEQ predicate on the "team_id" field.
func TeamIDNEQ(v string) predicate.Slack {
	return predicate.Slack(sql.FieldNEQ(FieldTeamID, v))
}

// TeamIDIn applies the In predicate on the "team_id" field.
func TeamIDIn(vs ...string) predicate.Slack {
	return predicate.Slack(sql.FieldIn(FieldTeamID, vs...))
}

// TeamIDNotIn applies the NotIn predicate on the "team_id" field.
func TeamIDNotIn(vs ...string) predicate.Slack {
	return predicate.Slack(sql.FieldNotIn(FieldTeamID, vs...))
}

// TeamIDGT applies the GT predicate on the "team_id" field.
func TeamIDGT(v string) predicate.Slack {
	return predicate.Slack(sql.FieldGT(FieldTeamID, v))
}

// TeamIDGTE applies the GTE predicate on the "team_id" field.
func TeamIDGTE(v string) predicate.Slack {
	return predicate.Slack(sql.FieldGTE(FieldTeamID, v))
}

// TeamIDLT applies the LT predicate on the "team_id" field.
func TeamIDLT(v string) predicate.Slack {
	return predicate.Slack(sql.FieldLT(FieldTeamID, v))
}

// TeamIDLTE applies the LTE predicate on the "team_id" field.
func TeamIDLTE(v string) predicate.Slack {
	return predicate.Slack(sql.FieldLTE(FieldTeamID, v))
}

// TeamIDContains applies the Contains predicate on the "team_id" field.
func TeamIDContains(v string) predicate.Slack {
	return predicate.Slack(sql.FieldContains(FieldTeamID, v))
}

// TeamIDHasPrefix applies the HasPrefix predicate on the "team_id" field.
func TeamIDHasPrefix(v string) predicate.Slack {
	return predicate.Slack(sql.FieldHasPrefix(FieldTeamID, v))
}

// TeamIDHasSuffix applies the HasSuffix predicate on the "team_id" field.
func TeamIDHasSuffix(v string) predicate.Slack {
	return predicate.Slack(sql.FieldHasSuffix(FieldTeamID, v))
}

// TeamIDEqualFold applies the EqualFold predicate on the "team_id" field.
func TeamIDEqualFold(v string) predicate.Slack {
	return predicate.Slack(sql.FieldEqualFold(FieldTeamID, v))
}

// TeamIDContainsFold applies the ContainsFold predicate on the "team_id" field.
func TeamIDContainsFold(v string) predicate.Slack {
	return predicate.Slack(sql.FieldContainsFold(FieldTeamID, v))
}

// SlackUserIDEQ applies the EQ predicate on the "slack_user_id" field.
func SlackUserIDEQ(v string) predicate.Slack {
	return predicate.Slack(sql.FieldEQ(FieldSlackUserID, v))
}

// SlackUserIDNEQ applies the NEQ predicate on the "slack_user_id" field.
func SlackUserIDNEQ(v string) predicate.Slack {
	return predicate.Slack(sql.FieldNEQ(FieldSlackUserID, v))
}

// SlackUserIDIn applies the In predicate on the "slack_user_id" field.
func SlackUserIDIn(vs ...string) predicate.Slack {
	return predicate.Slack(sql.FieldIn(FieldSlackUserID, vs...))
}

// SlackUserIDNotIn applies the NotIn predicate on the "slack_user_id" field.
func SlackUserIDNotIn(vs ...string) predicate.Slack {
	return predicate.Slack(sql.FieldNotIn(FieldSlackUserID, vs...))
}

// SlackUserIDGT applies the GT predicate on the "slack_user_id" field.
func SlackUserIDGT(v string) predicate.Slack {
	return predicate.Slack(sql.FieldGT(FieldSlackUserID, v))
}

// SlackUserIDGTE applies the GTE predicate on the "slack_user_id" field.
func SlackUserIDGTE(v string) predicate.Slack {
	return predicate.Slack(sql.FieldGTE(FieldSlackUserID, v))
}

// SlackUserIDLT applies the LT predicate on the "slack_user_id" field.
func SlackUserIDLT(v string) predicate.Slack {
	return predicate.Slack(sql.FieldLT(FieldSlackUserID, v))
}

// SlackUserIDLTE applies the LTE predicate on the "slack_user_id" field.
func SlackUserIDLTE(v string) predicate.Slack {
	return predicate.Slack(sql.FieldLTE(FieldSlackUserID, v))
}

// SlackUserIDContains applies the Contains predicate on the "slack_user_id" field.
func SlackUserIDContains(v string) predicate.Slack {
	return predicate.Slack(sql.FieldContains(FieldSlackUserID, v))
}

// SlackUserIDHasPrefix applies the HasPrefix predicate on the "slack_user_id" field.
func SlackUserIDHasPrefix(v string) predicate.Slack {
	return predicate.Slack(sql.FieldHasPrefix(FieldSlackUserID, v))
}

// SlackUserIDHasSuffix applies the HasSuffix predicate on the "slack_user_id" field.
func SlackUserIDHasSuffix(v string) predicate.Slack {
	return predicate.Slack(sql.FieldHasSuffix(FieldSlackUserID, v))
}

// SlackUserIDEqualFold applies the EqualFold predicate on the "slack_user_id" field.
func SlackUserIDEqualFold(v string) predicate.Slack {
	return predicate.Slack(sql.FieldEqualFold(FieldSlackUserID, v))
}

// SlackUserIDContainsFold applies the ContainsFold predicate on the "slack_user_id" field.
func SlackUserIDContainsFold(v string) predicate.Slack {
	return predicate.Slack(sql.FieldContainsFold(FieldSlackUserID, v))
}

// DisplayNameEQ applies the EQ predicate on the "display_name" field.
func DisplayNameEQ(v string) predicate.Slack {
	return predicate.Slack(sql.FieldEQ(FieldDisplayName, v))
}

// DisplayNameNEQ applies the NEQ predicate on the "display_name" field.
func DisplayNameNEQ(v string) predicate.Slack {
	return predicate.Slack(sql.FieldNEQ(FieldDisplayName, v))
}

// DisplayNameIn applies the In predicate on the "display_name" field.
func DisplayNameIn(vs ...string) predicate.Slack {
	return predicate.Slack(sql.FieldIn(FieldDisplayName, vs...))
}

// DisplayNameNotIn applies the NotIn predicate on the "display_name" field.
func DisplayNameNotIn(vs ...string) predicate.Slack {
	return predicate.Slack(sql.FieldNotIn(FieldDisplayName, vs...))
}

// DisplayNameGT applies the GT predicate on the "display_name" field.
func DisplayNameGT(v string) predicate.Slack {
	return predicate.Slack(sql.FieldGT(FieldDisplayName, v))
}

// DisplayNameGTE applies the GTE predicate on the "display_name" field.
func DisplayNameGTE(v string) predicate.Slack {
	return predicate.Slack(sql.FieldGTE(FieldDisplayName, v))
}

// DisplayNameLT applies the LT predicate on the "display_name" field.
func DisplayNameLT(v string) predicate.Slack {
	return predicate.Slack(sql.FieldLT(FieldDisplayName, v))
}

// DisplayNameLTE applies the LTE predicate on the "display_name" field.
func DisplayNameLTE(v string) predicate.Slack {
	return predicate.Slack(sql.FieldLTE(FieldDisplayName, v))
}

// DisplayNameContains applies the Contains predicate on the "display_name" field.
func DisplayNameContains(v string) predicate.Slack {
	return predicate.Slack(sql.FieldContains(FieldDisplayName, v))
}

// DisplayNameHasPrefix applies the HasPrefix predicate on the "display_name" field.
func DisplayNameHasPrefix(v string) predicate.Slack {
	return predicate.Slack(sql.FieldHasPrefix(FieldDisplayName, v))
}

// DisplayNameHasSuffix applies the HasSuffix predicate on the "display_name" field.
func DisplayNameHasSuffix(v string) predicate.Slack {
	return predicate.Slack(sql.FieldHasSuffix(FieldDisplayName, v))
}

// DisplayNameIsNil applies the IsNil predicate on the "display_name" field.
func DisplayNameIsNil() predicate.Slack {
	return predicate.Slack(sql.FieldIsNull(FieldDisplayName))
}

// DisplayNameNotNil applies the NotNil predicate on the "display_name" field.
func DisplayNameNotNil() predicate.Slack {
	return predicate.Slack(sql.FieldNotNull(FieldDisplayName))
}

// DisplayNameEqualFold applies the EqualFold predicate on the "display_name" field.
func DisplayNameEqualFold(v string) predicate.Slack {
	return predicate.Slack(sql.FieldEqualFold(FieldDisplayName, v))
}

// DisplayNameContainsFold applies the ContainsFold predicate on the "display_name" field.
func DisplayNameContainsFold(v string) predicate.Slack {
	return predicate.Slack(sql.FieldContainsFold(FieldDisplayName, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.Slack {
	return predicate.Slack(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.Slack {
	return predicate.Slack(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.Slack {
	return predicate.Slack(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.Slack {
	return predicate.Slack(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.Slack {
	return predicate.Slack(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.Slack {
	return predicate.Slack(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.Slack {
	return predicate.Slack(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.Slack {
	return predicate.Slack(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.Slack {
	return predicate.Slack(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.Slack {
	return predicate.Slack(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.Slack {
	return predicate.Slack(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailIsNil applies the IsNil predicate on the "email" field.
func EmailIsNil() predicate.Slack {
	return predicate.Slack(sql.FieldIsNull(FieldEmail))
}

// EmailNotNil applies the NotNil predicate on the "email" field.
func EmailNotNil() predicate.Slack {
	return predicate.Slack(sql.FieldNotNull(FieldEmail))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.Slack {
	return predicate.Slack(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.Slack {
	return predicate.Slack(sql.FieldContainsFold(FieldEmail, v))
}

// PictureEQ applies the EQ predicate on the "picture" field.
func PictureEQ(v string) predicate.Slack {
	return predicate.Slack(sql.FieldEQ(FieldPicture, v))
}

// PictureNEQ applies the NEQ predicate on the "picture" field.
func PictureNEQ(v string) predicate.Slack {
	return predicate.Slack(sql.FieldNEQ(FieldPicture, v))
}

// PictureIn applies the In predicate on the "picture" field.
func PictureIn(vs ...string) predicate.Slack {
	return predicate.Slack(sql.FieldIn(FieldPicture, vs...))
}

// PictureNotIn applies the NotIn predicate on the "picture" field.
func PictureNotIn(vs ...string) predicate.Slack {
	return predicate.Slack(sql.FieldNotIn(FieldPicture, vs...))
}

// PictureGT applies the GT predicate on the "picture" field.
func PictureGT(v string) predicate.Slack {
	return predicate.Slack(sql.FieldGT(FieldPicture, v))
}

// PictureGTE applies the GTE predicate on the "picture" field.
func PictureGTE(v string) predicate.Slack {
	return predicate.Slack(sql.FieldGTE(FieldPicture, v))
}

// PictureLT applies the LT predicate on the "picture" field.
func PictureLT(v string) predicate.Slack {
	return predicate.Slack(sql.FieldLT(FieldPicture, v))
}

// PictureLTE applies the LTE predicate on the "picture" field.
func PictureLTE(v string) predicate.Slack {
	return predicate.Slack(sql.FieldLTE(FieldPicture, v))
}

// PictureContains applies the Contains predicate on the "picture" field.
func PictureContains(v string) predicate.Slack {
	return predicate.Slack(sql.FieldContains(FieldPicture, v))
}

// PictureHasPrefix applies the HasPrefix predicate on the "picture" field.
func PictureHasPrefix(v string) predicate.Slack {
	return predicate.Slack(sql.FieldHasPrefix(FieldPicture, v))
}

// PictureHasSuffix applies the HasSuffix predicate on the "picture" field.
func PictureHasSuffix(v string) predicate.Slack {
	return predicate.Slack(sql.FieldHasSuffix(FieldPicture, v))
}

// PictureIsNil applies the IsNil predicate on the "picture" field.
func PictureIsNil() predicate.Slack {
	return predicate.Slack(sql.FieldIsNull(FieldPicture))
}

// PictureNotNil applies the NotNil predicate on the "picture" field.
func PictureNotNil() predicate.Slack {
	return predicate.Slack(sql.FieldNotNull(FieldPicture))
}

// PictureEqualFold applies the EqualFold predicate on the "picture" field.
func PictureEqualFold(v string) predicate.Slack {
	return predicate.Slack(sql.FieldEqualFold(FieldPicture, v))
}

// PictureContainsFold applies the ContainsFold predicate on the "picture" field.
func PictureContainsFold(v string) predicate.Slack {
	return predicate.Slack(sql.FieldContainsFold(FieldPicture, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Slack {
	return predicate.Slack(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Slack {
	return predicate.Slack(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Slack) predicate.Slack {
	return predicate.Slack(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Slack) predicate.Slack {
	return predicate.Slack(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Slack) predicate.Slack {
	return predicate.Slack(sql.NotPredicates(p))
}
